### ISSUE TITLE
[Suggestion] Nutrition Decay Independent of Hunger

### ISSUE THREAD

**Issue by Endgineer** [WesCook/Nutrition#100]
Would it be possible to have a config option for nutrition decay that is independent of hunger (periodic nutrition decay)? The thing is, I use the mod "Hunger Strike" to disable hunger completely because losing hearts or the ability to sprint for not eating sucks. I found that Nutrition makes eating beneficial- but the thing is, the nutrition values do not decay without hunger decaying. :S

**Comment by WesCook** [comment]
I'm not sure if I'd like to offer this as an official feature of Nutrition, but possibly once the API is ready it could be an addon mod.

I can't make any promises but I'll keep this feature in mind.

**Comment by WesCook** [comment]
This is more suited to API functionality so I'm going to close this request for now.  Thank you though for the suggestion.
