### ISSUE TITLE
Fossils and Archaeology support

### ISSUE THREAD

**Issue by Sunconure11** [WesCook/Nutrition#102]
Setting a reminder here for myself since it has now entered private beta testing on 1.12.2. Also, this would be one hell of a thing to set up, just from the sheer amount of meats alone.

**Comment by WesCook** [comment]
I looked around but it seems this is still in private testing.  As support isn't currently possible to add, I'm going to close this issue for now.  Please feel free to re-open it once the mod is officially released.
