### ISSUE TITLE
Culinary Construct

### ISSUE THREAD

**Issue by LokyLive** [WesCook/Nutrition#103]
Hello could you add support to the mod Culinary Construct please ? 

[link to the mod page](https://minecraft.curseforge.com/projects/culinary-construct?gameCategorySlug=mc-mods&projectID=296676)

**Comment by WesCook** [comment]
Hi,

Due to the complexity of these foods, support for this mod can only be implemented through an API.  Please see #74 for discussion on that.

I'm going to close this issue as TheIllusiveC4 is already involved in that discussion.

Thank you.
