### ISSUE TITLE
Config Option: exclude_bat_meat and exclude_bear_meat

### ISSUE THREAD

**Issue by An-Sar** [WesCook/Nutrition#106]
these would be useful to match the other meat specific configs. thank you

**Comment by WesCook** [comment]
Hello,

Can you please clarify your request?  Are you suggesting additional ore dictionary entries be added to the default protein.json file, or is this a request for an actual mod config setting?

Please elucidate if you could.  Thank you.

**Comment by An-Sar** [comment]
my bad, i had both your tracker and vanillafoodpantry up at the same time and placed the issue on the wrong page =/ sorry about that
