### ISSUE TITLE
[Suggestion] Hidden bars and hidden tooltips

### ISSUE THREAD

**Issue by Alessandro404** [WesCook/Nutrition#109]
As you may guess, I'm trying to make a pretty complex system

Gregtech 6 (1.7.10) Implement hidden values that check things like caffeine or cholesterol in the player. Drinking coffee or eating butter will give you speed bonuses or an heart attack if done too much.

I would like to have a lot of those values, but not overwhelm the player with values that are only useful for custom mechanics. 
That would require an hidden bar I guess, and a way to hid tooltips (Don't care If i need to write custom tooltips for every food manually).

**Comment by WesCook** [comment]
I think this would be doable...  Again, no promise on ETA.

**Comment by WesCook** [comment]
I've added this feature in the newly-released [v4.0.0](https://github.com/WesCook/Nutrition/releases/tag/v4.0.0).  Documentation will be updated soon, but you can see [example.json](https://github.com/WesCook/Nutrition/blob/1.12/src/main/resources/assets/nutrition/configs/nutrients/example.json#L6) for how it should look.
