### ISSUE TITLE
Salty mod support needs updating

### ISSUE THREAD

**Issue by Sunconure11** [WesCook/Nutrition#111]

**Comment by WesCook** [comment]
Tasks are starting to pile up...  going to need to spend a few days working through these.

**Comment by WesCook** [comment]
SaltyMod has been updated in [v4.0.0](https://github.com/WesCook/Nutrition/releases/tag/v4.0.0).

This one was tricksy.  It only adds some item IDs when Twilight Forest and Biomes o' Plenty are added.  Took me a while to understand why my logs were so inconsistent.
