### ISSUE TITLE
[Suggestion] Support for Reliquary

### ISSUE THREAD

**Issue by TheDeviantCrafter** [WesCook/Nutrition#113]
It only adds one food, glowing bread.

**Comment by WesCook** [comment]
As this mod only adds one food, I've decided not to add official support.  Unfortunately each mod I officially support requires ongoing testing, and this can be very time consuming.  I appreciate your suggestion none-the-less.  Remember that you can still add local support to your favorite mods just by editing the configs on your end.

Thanks again for your suggestion.
