### ISSUE TITLE
[Suggestion] Player-specific configurations

### ISSUE THREAD

**Issue by Crowfooted** [WesCook/Nutrition#117]
The ability to configure nutrients per-player (based on player name) so that server admins can give certain players allergies, intolerances, special buffs associated with specific food groups, etc.

**Comment by WesCook** [comment]
Thanks for your suggestion.  Unfortunately this doesn't match my current design for Nutrition, so I don't plan to implement player-specific nutrients.

Potentially this could be faked by using command blocks to constantly set a specific player's nutrition to 50%, so they don't have any effects applied.
