### ISSUE TITLE
Suggestion: Plants Mega Pack Support

### ISSUE THREAD

**Issue by breadguyyy** [WesCook/Nutrition#119]
PMP is by the same author as RealWorld and includes the same plants and foods as RW but as a standalone mod. The only thing that needs to happen for full out of the box support is a change from realworld to pmp in the item ids.

**Comment by WesCook** [comment]
Thanks for the heads up.  If both are being maintained, I suppose it makes sense to just duplicate those entries for now.

**Comment by breadguyyy** [comment]
okay just checked closer and it looks like pmp actually has different ids for some the items as well. sorry about that ill edit them and send a pull request with a list of the correct ids

**Comment by breadguyyy** [comment]
sorry for the wait but i just put em in a hastebin
https://hastebin.com/gevofizera.bash

**Comment by WesCook** [comment]
Thanks.  I'll add them in manually during a future patch.

**Comment by WesCook** [comment]
It looks like your original suggestion was right, and PMP and RealWorld do share IDs.  RealWorld has just changed all of their IDs since I first implemented support.  I've gone ahead and replaced my IDs with your supplied IDs for both mods.

Thanks for putting those together!

**Comment by breadguyyy** [comment]
thank you for this wonderful mod, glad i could help!

**Comment by WesCook** [comment]
PMP and RealWorld have been updated in the freshly released [v4.0.0](https://github.com/WesCook/Nutrition/releases/tag/v4.0.0).
