### ISSUE TITLE
[Suggestion] A new tag for effects to not hide effects

### ISSUE THREAD

**Issue by Insane96** [WesCook/Nutrition#125]
There should be something like "show_effect" (defaulting to false) in an effect.json
Right now every effect has the `showParticles` field set to false: https://github.com/WesCook/Nutrition/blob/1.12/src/main/java/ca/wescook/nutrition/effects/EffectsManager.java#L23
I would like to let the player know that he has some effects (like weakness), maybe having `isAmbient` set to true would be even better so the particles are not in the way all the time.

**Comment by WesCook** [comment]
I'll play with this idea the next time I'm working with the mod.

Ideally I'd like it if I could add a setting to have the effect listed in the GUI, but that's defined in the effect itself, if memory serves.

**Comment by Insane96** [comment]
Ye, something like
```
{
	"potion": "minecraft:strength",
	"visibility": "HIDDEN"/"AMBIENT"/"VISIBLE"	//If potion effect should be hidden (default), show soft particles (like Beacon effects) or be visible like a normal potion effect
	"amplifier": 0,
}
```

**Comment by WesCook** [comment]
Yeah, I wish that were possible but I don't think it is.  At least not without hacky workarounds.

**Comment by Insane96** [comment]
Why isn't possible?

**Comment by WesCook** [comment]
I think I misinterpreted you.  I thought you were talking about it showing up in the GUI, but I now believe you were referring to the particles for all three states (visible, ambient, hidden).  In which case that should be possible.

**Comment by Insane96** [comment]
Yeah I mean the vanilla particles visibility

**Comment by WesCook** [comment]
This feature has been added in [v4.2.0](https://github.com/WesCook/Nutrition/releases/tag/v4.2.0).  See the wiki for details.

https://github.com/WesCook/Nutrition/wiki/Effects

Thanks for your suggestion!
