### ISSUE TITLE
Recalculating Nutrition after food values are altered by Hunger Overhaul or other mod

### ISSUE THREAD

**Issue by Vyraal1** [WesCook/Nutrition#127]
Trying to nerf the Plants 2 Pineapple in terms of how much Fruit % it provides, however it seems to recalculate Nutrition amounts after Hunger Overhaul edits the food values. 
![image](https://user-images.githubusercontent.com/26587049/50541802-5ff0a480-0b7b-11e9-8cc6-079637ec7eeb.png)
The picture above is after using Hunger Overhaul to nerf the pineapple amounts. Normally it would be somewhere around 9-10 hunger restored (4-5 whole shanks) for just the pineapple.

**Comment by WesCook** [comment]
Hi Vyraal,

I've seen this question before.  I believe this comment should answer it:  https://github.com/WesCook/Nutrition/issues/98#issuecomment-431634999

Let me know if you have any other questions.

Thank you.
