### ISSUE TITLE
F4, F5, F6, F7, F8, F9, F10, F11 and F12 all open the Nutrition GUI if the key is unbound

### ISSUE THREAD

**Issue by TheDeviantCrafter** [WesCook/Nutrition#128]
By default, the Nutrition GUI is bound to N. It works as intended when it stays bound. If the key is unbound, all of the F keys except F1, F2 and F3 open the GUI.

**Comment by WesCook** [comment]
That's odd.  Thanks for your report, I'll take a look.

**Comment by WesCook** [comment]
I've tested this out and haven't been able to reproduce the issue.  Does this happen in a specific pack, or when paired with another mod?

Can you also tell me which version of the mod you're using?  v3.5.0 improved how key handling works.  If you're using an older version, please update.  Thank you.

**Comment by WesCook** [comment]
Due to lack of updates or reproduction, I'll assume this is not a current issue.
