### ISSUE TITLE
[suggestion] Support for nuclearcraft?

### ISSUE THREAD

**Issue by HeavyDeception** [WesCook/Nutrition#129]
Just what the name says.

**Comment by HeavyDeception** [comment]
Also if this is not able to happen would it be possible to add a command to add a value in game or on the fly? kind of like the EMC command for ProjectE also is it not possible to have it look for things like (if this item can be eaten add Nutrition if the name contains chocolate (Steak, or something like that ) add the correct type of value for that word kind of like how the Morphing tool & akashic tome work?

**Comment by WesCook** [comment]
Does NuclearCraft have many foods?  I usually skip mods that only have one or two food entries to reduce maintenance time.

As for your other suggestion, you need to edit the json files but the newest version of the mod does add a reload command.  Currently it only works in singleplayer.  The ore dictionary is supported for adding foods by grouping though (eg. foodSteak, foodChocolate).

I'm not sure I understand about the Morphing tool.

**Comment by HeavyDeception** [comment]
ok Thanks and after looking through NuclearCraft it looks like it may not have as many as I thought. So you should be ok to skip it.
