### ISSUE TITLE
option to specify the amount added with the cumulative detection option

### ISSUE THREAD

**Issue by EnderiumSmith** [WesCook/Nutrition#13]
some effects might not scale well with +1 level at a time and sometimes a negative level is required. for example for each nutrient bellow 10% remove 2 hearts using a negative level of heath boost. most vanilla effects work with negative levels.

**Comment by WesCook** [comment]
Hrmm, that's an interesting point.

Regarding granularity, are there many effects that don't scale well?  Health boost and absorption are the only two I can think of - at least in vanilla - and those were mainly addressed by the [Toughness effect](https://github.com/WesCook/Nutrition/wiki/Frequently-Asked-Questions#what-is-the-toughness-potion-effect).

Regarding negative values, effects seem to generally have a negative counterpart where applicable.  eg. strength vs weakness, or speed vs slowness.  With the exception again of health boost.

If I were to add a custom effect for health loss (opposite of Toughness), would this solve most use cases without requiring a change to the JSONs?  Granularity would probably be -1 heart per level, so minimum nutrition would be half health.

I wouldn't mind adding support for a feature like this, but I also want to be careful when adding complexity to be sure it's worth the tradeoff.

**Comment by EnderiumSmith** [comment]
there isnt a negative counterpart for jump boost, resistance and health boost. also modded effects.
i think it would be better to have an increment option. default to +1 if not specified. best to make it an integer.

also maybe add a version of health boost that adds 1HP per level instead of 4. for more precise health bonuses. and it does not conflict with heath boost potions.

**Comment by WesCook** [comment]
[v1.5.0](https://github.com/WesCook/Nutrition/releases/tag/v1.5.0) addresses this.  I added a `cumulative_modifier` property for specifying how much should be added or subtracted per cumulative level.

There's also new nourished/malnourished effects, which will add/subtract one heart per level.  This should allow for the desired levels of granularity.

You can use `nutrition:nourished` or `nutrition:malnourished` to specify them in the configs.

**Comment by WesCook** [comment]
Just to update this issue, I've since adjusted the mal/nourished effects so they apply half-hearts instead of full hearts.  This grants more control over granularity, at the cost of requiring a change to amplifier levels.

This change is in [v3.0.0](https://github.com/WesCook/Nutrition/releases/tag/v3.0.0) (thus the updated major version number).
