### ISSUE TITLE
Extra 4 hearts after death

### ISSUE THREAD

**Issue by darthvader45** [WesCook/Nutrition#131]
Seems some part of the toughness effect lasts after death.  I had toughness 2, and when I died, the potion effect went away as expected, but I still had the extra 4 hearts it gave me, apparently treating them like regular hearts.  It's like that other one issue (#63), but instead of being simply a graphical error, it's completely functional (they regen and everything).  

Minecraft 1.12.2
Nutrition version 3.5.0
Forge 14.23.5.2768

**Comment by WesCook** [comment]
Thanks for your report.  This sounds difficult to debug without exact steps to reproduce.  Attributes (like hearts) in Minecraft can be a little flaky and hard to manage.

Can you test if additional deaths have any effect?  How about restarting the game?

**Comment by darthvader45** [comment]
I've died several times.  Also, restarting the game has no effect.

**Comment by WesCook** [comment]
Okay, thanks.  Can you also rule out that your hearts aren't coming from another source?  eg. armor, potions, beacons, etc.

Would it be feasible for you to upload your save file, and link to your modpack?  I'm not sure how else to determine what else might be happening.

**Comment by darthvader45** [comment]
It's on a server, so it may be a server-side issue.  As such, I can't upload the save, only link the modpack (https://minecraft.curseforge.com/projects/technicians-survival-2).

**Comment by WesCook** [comment]
Okay.  Thanks for providing what information you can.  Unfortunately I think it's unlikely I'll be able to address this without the ability to reproduce the issue or examine an affected save however.

If I have time I'll poke around in the modpack to see if I can reproduce.  My guess is though that it's just a random, hard-to-reproduce event.

I imagine you won't be upset about the four extra hearts, in the mean time?  Hopefully gaining Toughness again will kick it back into gear, and sync back up.

**Comment by darthvader45** [comment]
It's on a server, so it may be a server-side issue.  As such, I can't upload the save, only link the modpack (https://minecraft.curseforge.com/projects/technicians-survival-2).

**Comment by darthvader45** [comment]
Nah, getting toughness again just gave me the usual extra hearts, on top of the possible glitch hearts.  No sync.

**Comment by darthvader45** [comment]
Nah, getting toughness again just gave me the usual extra hearts, on top of the possible glitch hearts.  No sync.

**Comment by WesCook** [comment]
I release a [new version](https://github.com/WesCook/Nutrition/releases/tag/v4.1.0) today that includes a fix to effects not being applied consistently on servers.  I don't know if it's the same bug that you ran into, but it's possible it could resolve it.  I'd suggest upgrading if you're able to.

Outside of that I'm not sure how I can address this bug report.  Unfortunately with no way to reproduce, I can only guess at what might have happened.  For that reason I'm going to mark this as closed for now.

Thank you for the report though.  I'll still be able to reference this bug report if similar issues crop up in the future.
