### ISSUE TITLE
Pam's hazelnut has no food group

### ISSUE THREAD

**Issue by renadi** [WesCook/Nutrition#132]
As titled, noticed no food group on hazelnuts, I ate half a dozen and saw no change in nutrition afterwards.

**Comment by mcdodge34** [comment]
There's a lot of recipes from Pam's Harvestcraft that don't have nutrients in them yet, not sure if anyone did some new ones recently, if anyone know of a new nutrients file with more food from Pam's supported, I would love it, for now, I'm ok with the choices we have, but it could be improved.

**Comment by WesCook** [comment]
It's been a few months since I've updated Harvestcraft support.  She adds new foods often, so it requires a lot of maintenance.  I am happy to merge pull requests for any mod updates though.

**Comment by WesCook** [comment]
Hi @renadi,

I tested this today and Hazelnut definitely has nutrients added (protein).  It's likely you just need to update your Nutrition configs.  They won't update automatically just in case you customize them.  You can simply delete the /configs/nutrition/nutrients folder to regenerate them.

Cheers.
