### ISSUE TITLE
Mod Tiny Progression

### ISSUE THREAD

**Issue by IncoGNikto** [WesCook/Nutrition#133]
Friend could you add to support fashion food from fashion Tiny progress. many assemblies are used together but food from Tiny does not count towards the Nutrition table

**Comment by WesCook** [comment]
Hi Inco,

Do you know how many foods Tiny Progressions offers?  I try not to add mods that only have one or two foods, because it still adds a lot of time to my upkeep.  So based on that I'll consider adding support or not.

Cheers.

**Comment by IncoGNikto** [comment]
I could count 40+ food items

**Comment by WesCook** [comment]
Thanks, appreciated.

**Comment by WesCook** [comment]
[v4.2.0](https://github.com/WesCook/Nutrition/releases/tag/v4.2.0) is out now with support for Tiny Progression.

**Comment by IncoGNikto** [comment]
Bro, la nourriture de Tiny Prorgession ne va pas dans les statistiques, j'ai essayé de manger des baies et une pomme au four, pas un pour cent n'a été ajouté aux statistiques  :С

**Comment by WesCook** [comment]
Did you clear your existing `/config/nutrition/nutrients/` directory after updating?

**Comment by IncoGNikto** [comment]
no, I completely forgot about it, cleared the config, everything worked, thanks))

Sorry what's off topic you do not know how to do so that I could have not 20 hearts but more? I have a Cyclic mod and together with your mod I can only have 20 hearts, although each of the mods allows you to add +10 hearts, I can not find information on this issue

**Comment by WesCook** [comment]
Nutrition's additional hearts should be compatible with other mods.  Are they not working together?

I haven't tested with Cyclic specifically, but I know *Spice of Life: Carrot Edition* works well with Nutrition.

**Comment by IncoGNikto** [comment]
hi bro, I noticed that in the fashion tiny progress you have not added some food to nutrition, although they are present in the crafting of already added dishes :)

**Comment by WesCook** [comment]
It's possible I missed some foods.  Or sometimes ingredients are implemented in a special way that Nutrition can't support.  Can you give some examples of what foods are missing so I can investigate?  Thanks!
