### ISSUE TITLE
Hud

### ISSUE THREAD

**Issue by IncoGNikto** [WesCook/Nutrition#134]
Bro could you make the output scale nutrition as the hud bar somewhere in the corner of the screen that would be a little easier to follow for those that need to eat, and then it turns out that sometimes forget to open the bar and one of the scales of diet falls very much, I think it would be helpful, a lot of people would appreciate this, because a lot of assemblies uses nutrition

P.s sorry for terrible English

**Comment by WesCook** [comment]
Hey @IncoGNikto,

Thanks for your suggestion.  On thinking it over, I've decided not to add a HUD at this time.

I can understand that it would be useful for some, but it may be considered obtrusive by others.  I'd likely want to have it disabled by default as I like to think of the nutrition system operating mostly in the background.  That however means adding a lot of code for a feature which would be disabled for 95% of users, which doesn't make a lot of sense to me.

Thank you for the suggestion regardless.  I'm not ruling it out completely, I just don't have any current plans to add it.
