### ISSUE TITLE
support for culinary construct please

### ISSUE THREAD

**Issue by Late-Night** [WesCook/Nutrition#135]
support for culinary construct and its addon please

https://minecraft.curseforge.com/projects/culinary-construct
https://minecraft.curseforge.com/projects/sauceconstruct

**Comment by TheIllusiveC4** [comment]
Nutrition support has been added in the 1.3.2 version of Culinary Construct.

**Comment by WesCook** [comment]
Because I've been a bum and haven't been working on the API.  Thank you for adding support on your end, Illusive.

**Comment by Dimentive** [comment]
@TheIllusiveC4 Awesome! Thank you! 💙
