### ISSUE TITLE
crash because of my own code (maybe)

### ISSUE THREAD

**Issue by zEpiixz** [WesCook/Nutrition#140]
So i tried to add a new type but it crashed.
https://paste.dimdev.org/yipujiyuji.mccrash

Heres my code:
https://pastebin.com/Wq26QHFs
now set to false.

PS: If you could and add cuisine support? Thanks.

**Comment by WesCook** [comment]
>"icon": "minecraft:brown_mushroom@0"

Does dropping the `@0` prevent the crash?

>PS: If you could and add cuisine support? Thanks.

There should be support added from their end.

**Comment by zEpiixz** [comment]
Thanks for the super fast response. 
Sadly yes:
https://paste.dimdev.org/hirozoduna.mccrash

**Comment by WesCook** [comment]
Looks like you're actually missing a closing brace.

**Comment by zEpiixz** [comment]
ahh that was it. Should have seen it myself thank you alot for your time :)
Only thing i have to ask now is why the name is nutrient.nutrition:Fungi instead of just fungi?

**Comment by WesCook** [comment]
No real reason.  Just a lack of planning and understanding of the localization system at the time.
