### ISSUE TITLE
Suggestion: add little warning sign next to nutrition button when you get the debuff

### ISSUE THREAD

**Issue by WeaselOnaStick** [WesCook/Nutrition#146]
I think a little yellow triangle with exclamation point would suffice. Problem is, some people(me aswell when I first encountered the mod) don't ever open that menu and when they get a debuff, there's no sign of what's happening.

**Comment by WesCook** [comment]
Adding more visual feedback is something I have in mind.  I'll leave this issue up as a reminder.

**Comment by Perruchy** [comment]
> I think a little yellow triangle with exclamation point would suffice. Problem is, some people(me aswell when I first encountered the mod) don't ever open that menu and when they get a debuff, there's no sign of what's happening.

Only an yellow warning sign ? Why not an yellow, orange and a red warning sign ?

**Comment by Perruchy** [comment]
And why not an yellow warning sign when you got debuff soon (like 5%...) and an orange warning sign when you are debuff ?
_I am bad in english RIP_

**Comment by WesCook** [comment]
While I think this is a really good feature request, I'm considering Nutrition in a maintenance state now and as such am not making any more big changes.  So I'm going to close this issue for now.

Thank you for the suggestion though.
