### ISSUE TITLE
Nutrition mod & Ender Utilities Slight problem

### ISSUE THREAD

**Issue by SirTwsted** [WesCook/Nutrition#147]
When using Handy Bag from Ender Utilities,
The nutrition button does not appear when pressing [E].
Would love to see the button so I can get into the nutritions panel to view my nutrition.
I will also post this on the Ender utilities GitHub so they will also know,
https://github.com/maruohon/enderutilities/issues/85
so both you guys can know of the small problem.
thanks.

**Comment by WesCook** [comment]
The nutrition button is added to instances of `GuiInventory`, which is the standard player GUI.  I'm guessing Ender Utilities is replacing it with their own GUI.  If possible they should extend it instead.  If that's not possible, then unfortunately there will be an inherent incompatibility.

As a workaround from Nutrition's side, you can still use the hotkey to open the GUI (default keybind 'N').

**Comment by WesCook** [comment]
I'm going to close this as it isn't something I can fix from my side.  Thanks for the report though.  It sounds like you have two workarounds available now.

**Comment by SirTwsted** [comment]
ok,  thank you. I will use the workaround [N] until Ender Utilities people can work on something for it.
thank you for taking the time out and looking into it.  appreciate very much  :D
