### ISSUE TITLE
Server crash with mod version 4.2.0

### ISSUE THREAD

**Issue by alfahundert** [WesCook/Nutrition#150]
Hello,

upon server start, it is crashing with the same error message.
On the client it loads up fine.

I've tested it with the latest(2814) and the last recommended(2768) forge version.
I also deleted the old config folder before server start.

Link to crashreport:
https://pastebin.com/sQVGSRjL

**Comment by WesCook** [comment]
You're completely right.  This is related to #138.  Shame on me for not testing the feature thoroughly.

**Comment by WesCook** [comment]
[v4.3.0](https://github.com/WesCook/Nutrition/releases/tag/v4.3.0) is out with the fix.

Your bug report has been solved in 30 minutes, so unfortunately the pizza is not free.

Pinging @NillerMedDild as this bug will affect them.

**Comment by NielsPilgaard** [comment]
Thanks for the ping, I appreciate it :) also, pizza please.
