### ISSUE TITLE
[Update Support] Vanilla Food Pantry

### ISSUE THREAD

**Issue by Akitori** [WesCook/Nutrition#151]
Howdy, the following items lack any nutrient values. This was found by a user, called @Tmtravlr who found all these foods in my modpack.

Cyclops sandwich
Jungle juju juice
Jar of condensed milk
Roasted veggies pocket
Grilled fish sandwich pocket
Cheesy batty burger - no dairy
Grilled cactus pad
Steamed cactus heart
Buttered bit ‘o bread
Sun butter with apples sandwich
Chocolate sun butter sandwich
SB&J Sandwich
Fish ball broth
Over-stuffed potato
Ugli fruit drink
Chocolicious icee

**Comment by Tmtravlr** [comment]
Well, the cheesy batty burger has a nutritional value, I just thought it strange that it didn't have dairy. There were a couple others like that if you want me to share those.

**Comment by WesCook** [comment]
Thanks for reporting those.  I've updated the foods listed above.  I have a method of checking for missing foods but it doesn't work with metadata. so those can slip by me.

If you know of any more foods that have incorrect or missing nutrients, please let me know.  I'll push a new update when that list is complete.

**Comment by WesCook** [comment]
The earlier additions have been included in the [v4.4.0](https://github.com/WesCook/Nutrition/releases/tag/v4.4.0) release.  If there are any others missing please let me know, but I'll mark this closed for now due to lack of followup.
