### ISSUE TITLE
Rustic Drinks

### ISSUE THREAD

**Issue by Renari** [WesCook/Nutrition#153]
Currently rustic drinks don't have any values, although I'm not sure the way the mod currently works supports these items.

`<rustic:fluid_bottle>.withTag({Fluid: {FluidName: "ironberryjuice", Amount: 1000}})`

All of the items are `rustic:fluid_bottle` with different fluids in them.

**Comment by WesCook** [comment]
Metadata is supported, but NBT data is not.  So there's unfortunately no method for supporting drinks like that at the moment.
