### ISSUE TITLE
[Request] Growthcraft Support

### ISSUE THREAD

**Issue by bookerthegeek** [WesCook/Nutrition#155]
# Heyo! # 
Wanted to drop in and let you know how much I am enjoying this mod (That it is not on CurseForge not so much but alas). Also if you would be able to spare a few moments to look into supporting the following mods;
 - [ ] [Baubley Heart Canisters][BHC] "One Item"
 - [ ] [Growthcraft Community Edition][GCE] " All food & Drinks"
 - [ ] [OpenBlocks][OPB] "Tasty Clay"
 - [ ] [IndustrialCraft 2][IC2] "Canned Food"

Thank you for taking the time to look into this for me. :)

[BHC]:https://minecraft.curseforge.com/projects/baubley-heart-canisters
[GCE]:https://minecraft.curseforge.com/projects/growthcraft-community-edition
[OPB]:https://minecraft.curseforge.com/projects/openblocks
[IC2]:https://minecraft.curseforge.com/projects/industrial-craft

**Comment by WesCook** [comment]
Thanks for your suggestions!  I'll need to look into each.  From a cursory glance, I'm most likely to add support for Growthcraft as it's a dedicated food mod.  For larger mods which only add one or two foods though, I'm less likely to add support as they're more difficult to maintain.

**Comment by bookerthegeek** [comment]
Gotcha. Is their a way (Config wise) for non coders to add that one-off support?

**Comment by WesCook** [comment]
Yes.  The configs were designed for that specifically.  Check out the wiki for details.

https://github.com/WesCook/Nutrition/wiki/Nutrients

**Comment by Deshiba** [comment]
Would there be a way to have support natively from the growthcraft side itself?

**Comment by WesCook** [comment]
A couple mods have added support by hooking in directly.  There's not an official API at the moment though.  See #74.

**Comment by captcookie** [comment]
May I add mod support for culinary construct? When I make sandwiches with it, it doesn't count towards nutrition. I have already requested on their end as well.

**Comment by WesCook** [comment]
As I understand @TheIllusiveC4 has already added support on their end.

https://github.com/WesCook/Nutrition/issues/135#issuecomment-460424366

**Comment by WesCook** [comment]
Growthcraft CE support has now been added in [v4.4.0](https://github.com/WesCook/Nutrition/releases/tag/v4.4.0).
