### ISSUE TITLE
[Suggestion] Support for Taco Tuesday and PizzaCraft

### ISSUE THREAD

**Issue by Dimentive** [WesCook/Nutrition#157]
Could Nutrition possibly be updated to support foods added by the [Taco Tuesday](https://minecraft.curseforge.com/projects/taco-tuesday) mod, by Kashdeya, by default? That would be fantastic, as Taco Tuesday is a great food mod!

**Comment by Dimentive** [comment]
[PizzaCraft](https://minecraft.curseforge.com/projects/pizzacraft) is a pretty popular mod, too. I’d love to also see integration with the pizzas from this mod!

**Comment by WesCook** [comment]
Support for both mods has been added in [v4.4.0](https://github.com/WesCook/Nutrition/releases/tag/v4.4.0).  Thanks for the suggestions!
