### ISSUE TITLE
[Update Support] Pam's Harvestcraft

### ISSUE THREAD

**Issue by Akitori** [WesCook/Nutrition#160]
Howdy! Pam's released a new update and all these items lack nutrition value (random side question, why does nether star on toast give so much nutrients?)

Soba Noodles, Tuna Onigiri, Salmon Onigiri, Taiyaki, Mochi Dessert, Mochi Cake, Imagawayaki, Shrimp Tempura, Gyudon, Strawberry Soufflé, Bratwurst, Schnitzel, Hot Cocoa, Chicken Biscuit, BBQ Chicken Biscuit, Zucchini Bake, Chocolate Coconut Bar, Vanilla Conchas Bread, Cinnamon Bread, Musubi, Fruit Cake, Bologna, Bologna Sandwich, Fried Bologna Sandwich, Cassoulet, Corn Chips, Battenberg, Pumpkin Spice Latte, Root Beer Float, Chili Dog, Peanut Soup, Gravlax, Cheese Danish, Chicken Cordon Bleu, Sunday High Tea, Cucumber Sandwich, Imitation Crab Sticks, Raspberry Milk Shake, Rice Pudding, River Mud Cake, Seed Energy Gel, Butter Tart, Marshmellow Chicks, Bacon Wrapped Chili, Mushroom Ketchup, Mushroom Ketchup Omelet, Bento Box, Fried Feast, Dandelion Salad, Dandelion Tea, Lychee Tea, Miso Paste, BBQ Jackfruit, BBQ Chicken Biscuit, Chicken Biscuit

**Comment by Dimentive** [comment]
>(random side question, why does nether star on toast give so much nutrients?)

Probably because Nether stars are hard to come by.

**Comment by WesCook** [comment]
>>why does nether star on toast give so much nutrients?

>Probably because Nether stars are hard to come by.

Pretty much!  Along with the Notch Apple, they include all nutrients for balance reasons rather than culinary.  I think these are the only two examples of that happening.

I've now updated Pam's support in [v4.4.0](https://github.com/WesCook/Nutrition/releases/tag/v4.4.0), so I'm marking this issue as closed.
