### ISSUE TITLE
[Suggestion] Potion of Nutrition

### ISSUE THREAD

**Issue by Insane96** [WesCook/Nutrition#161]
Gives back each second 0.1% (or 0.005% each tick, configurable) of a random nutrient. Lower nutrients have more chance to get the increase.
That would make a possible potion for nutrients without begin op.
The potion should be made with a Notch Apple (Enchanted Golden Apple) and the duration should be the one of a normal potion (3 minutes, configurable). Cannot be extended or made lvl 2.

**Comment by WesCook** [comment]
Would this be related to #124?

**Comment by Insane96** [comment]
Not really

**Comment by WesCook** [comment]
It sounds like you have a specific use-case in mind, but I don't believe there's enough demand to add this feature right now.

The biggest uses I can think of would be for quest book rewards, or in custom maps.  But there's hasn't been any other requests for this sort of feature.  I believe that custom commands are also at least a partial solution for these two use cases.

If other requests come in for a future similar to this though, I'll keep it in mind in the future.

As for use in regular survival play (eg. when crafted with a Notch apple), it's sort of against the spirit of the mod to apply a magical potion version of nutrition-gain.  An alternate approach might be to set the food value of Notch apples to very high (via another mod).  Golden apples already contain all nutrients, so it would grant a large amount of nutrition that way.

Hopefully these approaches can solve your need without requiring a new feature.
