### ISSUE TITLE
Add a way to manually set nutrition percentage for some foods

### ISSUE THREAD

**Issue by Insane96** [WesCook/Nutrition#162]
E.g. I would like to have more nutrition given by the Notch Apple, but right now you can't since Nutritional values are calculated by hunger.
Some kind of JSON with custom nutrition percentages or even Crafttweaker/modtweaker support.

**Comment by WesCook** [comment]
The topic has come up a number of times before, but allowing manual nutrition values isn't currently on the roadmap.  It just falls outside of the design for the mod.  Thank you for the suggestion though.

**Comment by Insane96** [comment]
At least make Milk Bucket configurable, since you can't reduce the "hunger" given by it.
