### ISSUE TITLE
[Mod Support update] XLFoodMod

### ISSUE THREAD

**Issue by LeoBeliik** [WesCook/Nutrition#163]
XLFood mod got an update and the next foods are lacking of nutrients: 

- rice_bread
- ham
- sausage_roll
- breakfast_sandwich
- grilled_cheese_sandwich
- marshmallow
- roasted_marshmallow
- bourbon_biscuit

Many thanks to you 😃

**Comment by WesCook** [comment]
Thanks!  Added to the list.

**Comment by WesCook** [comment]
It looks like only `xlfoodmod:rice_bread` and `xlfoodmod:ham` should be getting new nutrients.  The energy drinks have no food value set so they won't grant nutrition even if a category is assigned.  And the marshmallows are just crafted from sugar so they wouldn't have any nutrients either.

**Comment by WesCook** [comment]
The two additions listed above are now included in [v4.4.0](https://github.com/WesCook/Nutrition/releases/tag/v4.4.0).  The others have been omitted intentionally.
