### ISSUE TITLE
Configurable Nutrition Values

### ISSUE THREAD

**Issue by enbyminer** [WesCook/Nutrition#164]
Hi!  I'm pretty new to mods so hopefully this is the right place to ask this-

I'm trying to add different nutrients using your mod, such as carbs and fiber instead of grain and vegetable. Is there a way to specify how much of a nutrient each food provides, or is it automatic?  For example, harvestcraft:blackberry is 0.5% Fruit.  Can I set it to 1.79% Vitamin C? (Vitamin C being one of the nutrients I'd like to add.)

And thank you so much for this mod!  I'm not sure I'd even still be playing Minecraft if it weren't for you.

**Comment by WesCook** [comment]
Hey @enbyminer,

Thanks for your suggestion.  This is indeed the right place to ask questions and make suggestions.

Setting a specific value for foods isn't currently possible.  That is by the original design of the mod which made nutrition values based on hunger values.  This creates an inherent balance as hunger also reduces nutrition.

It's something I might be open to implementing in the future as it is a fairly popular request (see #162).  At this time though it's not in the cards.  I understand that makes your specific use-case more difficult, and I'm sorry there isn't a better solution there.

Thanks again for your suggestion, and I'm glad to hear you've been enjoying the mod!

**Comment by enbyminer** [comment]
Alright, thank you so much!  Sorry I missed #162 before writing this.
