### ISSUE TITLE
its op

### ISSUE THREAD

**Issue by AlphaFrog** [WesCook/Nutrition#170]
how do i reduce the affects of the nutrition like strength and resistance i put amplifier to 0.5 and it crashed please help me!!!!

**Comment by WesCook** [comment]
Amplifiers must be integers.  They are potion effect levels (eg. Strength 1).  As there is no Strength 0.5 it wouldn't be a valid potion effect.

You can fully customize the detection parameters to make effects harder to get (require more nutrition), or reduce the effects given.  Please see the wiki page for how to edit effects.

https://github.com/WesCook/Nutrition/wiki/Effects

Alternatively you can make nutrition drain more aggressively, or grant less nutrition from eating foods.  See the main configuration file for that.

If you have any more questions you can update this issue.

**Comment by AlphaFrog** [comment]
thank you
