### ISSUE TITLE
Suggestion: Release on Curseforge

### ISSUE THREAD

**Issue by IdrisQe** [WesCook/Nutrition#172]
This would be a great QoL addition, allowing people to more easily include your mod in modpacks, as well as giving it far more attention, as currently finding mods on github isn't really easy. You don't even necessarily need to release every version there. I know it would be less than ideal having it in two locations but it would make sense. Or perhaps if you don't like Curseforge, another site like Planetminecraft or something. Granted Curseforge would be ideal due to the API allowing several modpack managers to access it more easily but ah...

**Comment by WesCook** [comment]
Hi Idris,

Thanks for your suggestion.  However my decision to not host with Curse was a conscious one.  I'll try to explain briefly.

Curse has always been reluctant to offer support for third-party mods.  They currently use an "approved list" (which Nutrition is on), but have previously expressed interest in removing even this feature.  At that point the modded ecosystem would be locked to a singular platform.  Many obscure yet interesting mods could no longer be included in Curse-hosted modpacks.

I believe it's important that some mods remain available outside of Curse to keep pressure on them to allow third-party sources.

As for Planet Minecraft, I'm afraid it's just not a website I have any familiarity with.

I find GitHub works very well as a mod-hosting platform.  It emphasizes open-source, has an integrated issue tracker, and offers free hosting for releases.  For these reasons and those listed above, I'm going to continue to host with GitHub - at least for the time being.

Thank you again for your suggestion.

**Comment by MagmaSlime123** [comment]
You might as well just talk with them sbout this. The Technic Platform is similar to Curse but more about modpacks.
