### ISSUE TITLE
compatible Auto Feeder Helmet

### ISSUE THREAD

**Issue by axin0452** [WesCook/Nutrition#175]
It does not increase nutritional value when it is eaten automatically.

**Comment by WesCook** [comment]
Similar to this issue (https://github.com/WesCook/Nutrition/issues/159#issuecomment-482754407), I believe integration is required on the end of the auto-feeder mod.

Nutrition is checking that the food item is finished "being used".  If Auto Feeder can fire that same event, then mods that rely on event completions like Nutrition should start to work again.

So unfortunately I don't have a fix I can easily implement on my end.  But thank you for the report, and I apologize for the inconvenience.
