### ISSUE TITLE
Nutrition and ScalingHealth HUD display error

### ISSUE THREAD

**Issue by Abo233** [WesCook/Nutrition#180]

**Comment by WesCook** [comment]
Can you provide additional details?

**Comment by Abo233** [comment]
when you are poisoned，two health bars will be displayed
![2019-08-22_23 20 55](https://user-images.githubusercontent.com/54156635/63528053-d12efe80-c534-11e9-95c5-1fcb9cfb0a79.png)

**Comment by Abo233** [comment]
when you are just hurt,the health bar shows normal
 Only Show the bottom health bar

**Comment by Abo233** [comment]
when you are just hurt,the health bar shows normal

**Comment by Abo233** [comment]
Very interesting BUG

**Comment by WesCook** [comment]
Nutrition adds player health by modifying the player's max_health attribute.  That's the standard way of doing it, so it shouldn't be doing anything weird that would create multiple healthbars.

It's possible that ScalingHealth uses their own system for increasing player health.  In that case we may be using incompatible methods.  However I'm not familiar with the mod so it could also be a completely unrelated mod or interaction.

I'll ping @SilentChaos512 who authors ScalingHealth as they may know more.

In the mean time Abo, I'd suggest you check for any GUI-related mods that might be changing how healthbars are drawn.  I seem to remember Mantle did this at one time.

**Comment by Abo233** [comment]
Ok, I will try

**Comment by SilentChaos512** [comment]
Scaling Health also uses attributes, so that shouldn't be an issue. Seems more like a rendering issue. Two mods are trying to override the health bar at once.

**Comment by KnightMiner** [comment]
I'll chime in that Mantle still modifies the health bar. On the chance that is the issue, for compatibility our healthbar fires an event you can cancel to stop our renderer from running at all.

**Comment by Abo233** [comment]
May be special mobs mod

**Comment by WesCook** [comment]
Okay well I think we have enough evidence that it's not Nutrition or ScalingHealth at least, so I'll go ahead and mark this as closed.  Thanks to all that chimed in.
