### ISSUE TITLE
[Suggestion] CraftTweaker support

### ISSUE THREAD

**Issue by DreamThorn** [WesCook/Nutrition#182]
I see at least two possibilities that could help modpack makers to detect problems in their pack, so I am posting two suggestions.

Option 2: Is to add support for CraftTweaker brackets, getters and setters, so that we can write our own scripts for detecting or auto-calculating missing values.

**Comment by DreamThorn** [comment]
I'm keeping this suggestion despite my original problem being solved, since it would still be nice to be able to automate adding nutrition info to my pack.

**Comment by WesCook** [comment]
Could you clarify how CraftTweaker support would help in automation?  I've used it some but rarely the advanced features.

Specifically what problem does this solve that the existing logging features do not?

**Comment by DreamThorn** [comment]
For example, if there is a cooking mod that you don't already support, or if I add a lot of cooking recipes to my modpack using ContentTweaker, I could write a script that calculates each food item's nutrition values from that of its ingredients, instead of calculating it all by hand and typing it in.

**Comment by WesCook** [comment]
That's interesting.  I had no idea CraftTweaker was advanced enough to calculate such data from its registered recipes.

That currently sounds a little outside the scope of what I'd be willing to implement, but I consider it an interesting idea.  I might circle around to CraftTweaker support in the future.

Right now though it's not a priority, so I'm going to mark this issue as closed (but not locked) unless that changes.

Thanks for your suggestion!
