### ISSUE TITLE
NetherEx compatibility note

### ISSUE THREAD

**Issue by katubug** [WesCook/Nutrition#184]
Hello! Firstly, thank you for the fantastic mod! I was super stoked to see that you've updated. :D

I came by to mention that I was going through my configs and found

```
"nex:ghast_meat_cooked",
"nex:ghast_meat_raw",
```

It's very possible you've already fixed this, but in case it got missed, NetherEx recently changed the mod name from `nex` to `netherex`.

**Comment by WesCook** [comment]
That's new to me.  I'll make a note of that.  Thank you for reporting!

**Comment by WesCook** [comment]
I've updated this in the patch I'm working on now, which should be going out soon.
