### ISSUE TITLE
Culinary Construct Support?

### ISSUE THREAD

**Issue by EnzoIsPrettyCool** [WesCook/Nutrition#185]
Would it be possible to add support for [Culinary Construct](https://www.curseforge.com/minecraft/mc-mods/culinary-construct)? Like each ingredient adding to its individual food group?

**Comment by WesCook** [comment]
Support for that particular mod would have to be added via an API.  Work on an API was started, but was suspended as it was too large and difficult of a task at that time.  It's something that might come up in the future, but no promises at this time.

It's possible changes in 1.14 will also make it possible to support Culinary Construct without an API, as meta values will be going away in favour of NBT.

---

To add, TheIllusiveC4 has already added support for Nutrition on their end in v1.3.2.
