### ISSUE TITLE
Pam's Brewcraft support

### ISSUE THREAD

**Issue by brisingraerowing** [WesCook/Nutrition#188]
[Mod link](https://www.curseforge.com/minecraft/mc-mods/pams-brewcraft)

Adds a bunch of alcoholic drinks. Not sure if compat would actually be useful or not.

**Comment by WesCook** [comment]
Pam's BrewCraft support is added in the latest update ([available now](https://github.com/WesCook/Nutrition/releases/tag/v4.6.0)).
