### ISSUE TITLE
GUI Button conflict with Quark

### ISSUE THREAD

**Issue by BBoldt** [WesCook/Nutrition#19]
![](http://i.imgur.com/ThScxqj.png)

I realize you have a config option to disable the button, but I would like to keep the button. 

May I suggest a config option to move it near the top of the inventory GUI? 
Maybe right here:
![](http://i.imgur.com/YG2mUn4.png)

**Comment by KnightMiner** [comment]
Does Quark have configs to move their buttons? Would be good to have it on both sides anyways

**Comment by BBoldt** [comment]
Actually it looks like you can directly edit the position of the buttons in quark. Still, would be nice if they didn't conflict by default as i'm sure a lot of the people playing this mod will install quark as well.

**Comment by MechWarrior99** [comment]
I don't think that the button should go up there. It would look strange and disjointed if it was there because of the crafting book. Though I don't have an idea idea for a better spot. Just let pack makers move the quark buttons about I guess would be my suggestion.

**Comment by WesCook** [comment]
Well that's unfortunate.  I ended up moving the button more to the right to get out of the way of the recipe book, though I didn't consider that Quark would be there as well.

It looks like it would be a pretty snug fit between the player portrait and crafting grid.

I think the best look would be moving both the recipe book and nutrition buttons more to the left, and just leave Quark where it is.  I definitely don't want to move vanilla features around by default, but maybe behind a config option or Quark-detection mode.

Open to thoughts on this one.

**Comment by WesCook** [comment]
It is indeed a snug fit, but it's now available to you in [v2.2.0](https://github.com/WesCook/Nutrition/releases/tag/v2.2.0).

![snug](https://user-images.githubusercontent.com/792101/28983644-8b375684-790f-11e7-8a6a-955b3c072157.png)

I decided to add an option to set the position manually in the configs.  This is preferable to adding special casing or specific mod support, as that may be a never-ending game of whack-a-mole.  This option should allow modpack authors to choose instead.

The specific values above are `X: 76, Y: 7`, by the way.

**Comment by BBoldt** [comment]
awesome! thanks.
