### ISSUE TITLE
Suggestion: Reverse Nutrition (ie, food that's "bad for you")/Foods that lower nutrition values

### ISSUE THREAD

**Issue by katubug** [WesCook/Nutrition#194]
I am working on a hardcore-ish modpack, and one of the things I thought could be really interesting was the need to balance eating enough good nutrients without overeating bad ones. The example I had in mind was sodium (I'm using the SaltyMod, but a lot of other mods add salt as well).

The way I'd envisioned doing this was having it behave inversely to other nutrients, where instead of getting debuffed when it was low, and buffed when it was high - you'd be debuffed if it got too high, and optionally buffed if you could keep it under a certain threshold. I can implement this partially in the configs by assigning negative debuffs to higher levels and vice versa, but it won't be a very elegant solution, so I thought I'd come by and write this up.

The one caveat I could think of was: there would need to be a way of lowering the nutrient if it got too high. The workaround I was going to use was to see if there was a debug command to set nutrient levels and have that fire when certain items were used - in terms of configs though, it would probably just be better to have certain food items (in the case of salt, I was thinking water/drinks) reduce that level.

The other thought I had regarding that would be to be able to adjust the decay of each nutrient separately, instead of all at once.

I am not sure if this is something that would interest you at all, or if you're even still maintaining this for 1.12, but I thought I would ask! In any case, thank you for the fantastic mod, and for taking the time to read this. I hope you're having a good holiday season!

**Comment by katubug** [comment]
Oh! I just noticed that you *can* set the decay separately from other nutrients! Perfect, I'm so excited :D

**Comment by KnightMiner** [comment]
The effects from a nutrient are entirely configurable. You can exclude the bad nutrient from the good effects and have bad effects that only happen when it is high.

**Comment by WesCook** [comment]
So, where does that leave us?  Is any required functionality missing at this point, @katubug?

**Comment by katubug** [comment]
I see that now! Then, really the only thing that isn't currently implemented is the "certain foods decrease certain nutrients" - but I think that's not really important if I can just boost the decay level.

**Comment by katubug** [comment]
Oh and, I'm not sure if this is worth making a separate thread over - but the nutrient I added seems to have an unlocalized name in GUI? "nutrient.nutrition:sodium" - is there a field I omitted somewhere? Or do I need to make a lang override for it?

**Comment by WesCook** [comment]
Need to override the localization string.

https://github.com/WesCook/Nutrition/wiki/Nutrients#localizations

**Comment by katubug** [comment]
Awesome, thank you very much! Sorry for the false alarm, I'll go ahead and close this. :)

**Comment by WesCook** [comment]
No sweat.  It makes me happy to see people customizing the mod like this.

**Comment by katubug** [comment]
I'm honestly really excited by how many possibilities these configs offer - the more I look, the more I realize I can leverage! So, thank you very much :D
