### ISSUE TITLE
Mod support

### ISSUE THREAD

**Issue by Romz24** [WesCook/Nutrition#195]
I propose to add support for some mods, when I try to register this in the config I unfortunately do not get any result.

- [ExtraPlanets](https://www.curseforge.com/minecraft/mc-mods/extraplanets)
```
extraplanets:canned_food
```

- [Atum 2](https://www.curseforge.com/minecraft/mc-mods/atum)
```
atun:date
atun:golden_date
atun:golden_date_enchanted
```

- [Industrial Craft](https://www.curseforge.com/minecraft/mc-mods/industrial-craft)
```
ic2:filled_tin_can
```

**Comment by WesCook** [comment]
I've tested each item.  The Atum 2 foods accepted nutrients as expected.  You may have a configuration error if they didn't work.

The ExtraPlanets canned food isn't a [real food item](https://github.com/MJRLegends/ExtraPlanets/blob/dev_1.12.2/src/main/java/com/mjr/extraplanets/items/ItemCannedFood.java#L27) so it cannot accept nutrients.

IC2 isn't open-source so I can't review it without decompiling, but I'd wager that its "filled tin can" isn't a proper food item either.
