### ISSUE TITLE
[Mod Support] Gamestage

### ISSUE THREAD

**Issue by Silverrain2004** [WesCook/Nutrition#196]
I have a little Problem... i have a little expertpack where my Players, explore through Ages. Now is it like
that.. if they beginn the Game, they have no stage... that means, they have no possibility to raise their nutrition... and you cant cook meals in that stage.. but nutrition is applied in every stage... and thats bad..

My suggestion is.. please add gamestage support, so i can setup a stage, where Nutrition is applied, instead of having Nutrition at the beginning. So i can say.. Nutrition mod beginns in Stage1 instead of the whole game.. so freshstarter have a chance to survive..

**Comment by WesCook** [comment]
There was a similar request for advancement support a while back (#21).  They had a similar use-case, but there didn't seem to be enough demand to justify the extra complexity required to add conditional support.  I'm afraid the same might be true here as well.

I might play around with the idea.  I'm not promising anything, and it won't be for a while, but I'll leave this open at least so I can test it later.  It'll probably require a new dependency which I'm not a big fan of.

**Comment by WesCook** [comment]
Note to self:

* Add compat folder.  GameStage check requires passing in player, returns if stage is reached.  If mod isn't found, always return true.
* Require new `game_stage` field in nutrient json.
* Investigate advancement logic to see if they can be included too with minimal work (using advancement ID in nutrient json).
* Should nutrients be hidden, or grayed out in GUI if unavailable?

**Comment by Silverrain2004** [comment]
Hi there Wescook! thank you for taking your time to look into it. I was surprised, that a reply was comming so fast :) so i mean positiv. ... If you can manage this, it would be awesome. If nutrients be grayed out would be a good choise. So Players can see they have to look into Nutrients , but not in their present stage, the intention is, to give the player time to gather knowledge and resources to cook better meals . There is a good API vor Gamestage, so i dont think it would be so hard to implement this feature. Also i think, many expertish Packs would benefit from it. If there is an even easier way to do this... like a config, or a command , i can make a Quest in BQ with a Commandreward. After the Commandreward, its like Nutrition turned on at this point. So either Gamestage would be decent... or a command if that makes things easier for you to implement.

**Comment by WesCook** [comment]
As newer Minecraft versions have largely supplanted 1.12, I'm not likely to add new features to Nutrition at this point.  So I'm going to go ahead and close this issue now.

Thanks for the suggestions all the same though, and I'm sorry I wasn't able to deliver on this particular request.
