### ISSUE TITLE
[1.12.2] Toughness does not reapply if effects are cleared via command

### ISSUE THREAD

**Issue by katubug** [WesCook/Nutrition#197]
Hi! I'm testing out some effects for various nutrition levels, and I'm currently working on balancing the health given by Toughness. I've set it to only apply when all of 4 nutrients are between 99-100%.

I got a random effect from somewhere (probably a blighted mob? idk) I used `/effect Katubug clear` to get rid of it, and the Toughness was cleared as well, and failed to reapply even though my nutrients were within the correct parameters.

Opening and closing the world does not fix it. Through a few tests, it seems the only way it can be fixed is either by completely exiting the client and starting back up (although I did change a config value related to it, so that could have been why), or to die and get your nutrition back up.

Obviously this is a pretty minor issue, because in theory survival players won't be using the effect command, and creative players won't care about their hearts, but I figured I'd mention!

Minecraft: 1.12.2
Nutrition: 4.4.0
Forge: 2847

Here's my toughness.json: https://pastebin.com/mf2LPmJx

If you need any other information or tests you'd like me to do, just let me know! I hope you are having an excellent holiday season. If you celebrate, Merry Christmas! And thanks yet again for such a fantastic mod.

**Comment by WesCook** [comment]
Hey, great bug report!  I appreciate the attention to detail.

I'll have to try it out as that shouldn't be happening.  The check to apply effects occurs every six seconds or so, and shouldn't be affected by commands.

One thought is that sometimes the player will get extra hearts, which the game then tries to fill up.  This uses hunger (via natural healing mechanic), which then drops their nutrition again.  I wonder if having such tight values (99-100%) is running into something like that.

I can't look into this right away, but I should have all the info I need to attempt to reproduce.  Thanks again for the detailed bug report.  Happy holidays!

**Comment by WesCook** [comment]
I tested this config file out today but unfortunately was not able to reproduce the issue.  After clearing the effects, the correct potion effects triggered as expected.

I thought the issue may be the so many hearts would necessitate hunger, and that would drop the nutrient levels below the threshold.  While that did occur, it wasn't enough to create the issue described above.

It's possible that another mod may be conflicting with how potions are applied.  That would be a larger issue, but isn't something I have enough information to go on.

So I'm going to mark this as closed.  However it you see any evidence of a conflict or other cause to this issue, let me know and I'll take another look.

Thanks again for the excellent bug report.
