### ISSUE TITLE
Incompatibility/Annoyance with Quark: nutrition button covers hover text for chest buttons in inventory

### ISSUE THREAD

**Issue by inkdear** [WesCook/Nutrition#198]
Edit: oops, no text. Anyway, here's a screenshot:
![great i love it](https://user-images.githubusercontent.com/41709276/71653685-af6f3f00-2d92-11ea-9b7a-acfb5c6abd64.png)

**Comment by WesCook** [comment]
Hi inkdear,

In the /config/nutrition/nutrition.cfg file, you'll find these lines:

    # The anchor defines which side of the origin to position the button against.
    # Accepted values: top, right, bottom, left, top-left, top-right, bottom-right, bottom-left, center [default: top-left]
    S:ButtonAnchor=top-left

    # The origin defines the object which the nutrition button will be placed relative to.
    # Accepted values: gui, screen [default: gui]
    S:ButtonOrigin=gui

    # The nutrition button's X position, relative to its anchor point. [range: -1000 ~ 1000, default: 134]
    I:ButtonXPosition=134

    # The nutrition button's Y position, relative to its anchor point. [range: -1000 ~ 1000, default: 61]
    I:ButtonYPosition=61

You can adjust the X and Y positions to move the button around, or use the other two settings to adjust its origin point (eg. where it starts).

I believe Quark also adds a way to move the button around.

**Comment by inkdear** [comment]
Hi! I am aware the buttons can be moved around - they have already been moved around in the screenshot. The problem is that the quark button tooltips stick out both sides (from each button), which makes fitting both on the UI difficult, even though it seems like they "should" fit (I realize this is subjective, but the interaction with the tooltip seemed objectively undesirable.)

I suspect that if this were to be remedied, it would be best done via a tooltip toggle config option on Quark's end, but I always report issues to all mods involved, just in case. Thank you for the response!

**Comment by WesCook** [comment]
Okay, thanks for further explaining that.  I didn't realize you were talking about the tooltip specifically.

I'm not too sure off the top of my head was determines the draw order.  That may be something Quark is able to override, but I can't think of anything I can adjust on my end to fix it.
