### ISSUE TITLE
Request:config option for the nutrition value of individual foods

### ISSUE THREAD

**Issue by mzldh** [WesCook/Nutrition#199]
Believe it or not I'm now trying to introduce a thirst system to my modpack with nutrition mod and my own custom made MCreator mod. however my biggest obstacle is the config of nutrition mod.

Nutrition values of a food item is dictate by the hunger value it provides. This creates a great limitation for modpack creators.

If we can custom set individual nutrition values while saving the ability to have the general config, it'll make a lot more possibilities for the mod. :D

**Comment by WesCook** [comment]
Hi @mzldh,

Thanks for your request.  This is something I've talked a little bit about before in #164, but it's not something I'm planning to add support for at this time.  I'm sorry that this limits the functionality required for your pack.

I may revisit the issue during future updates, but that likely won't be for a while.

Thank you.
