### ISSUE TITLE
[Suggestion] Primal Core Support

### ISSUE THREAD

**Issue by TheLimePixel** [WesCook/Nutrition#20]
I suggest adding support for the Primal Core mod. Primal Core is a hardcore/realistic survival mod, which adds a lot of food, from Shark Meat to Corn Bread. As this mod is aimed at making hunger more realistic, it would work really well with it.

**Comment by Sunconure11** [comment]
Send a link and I'll be on it tomorrow/later today, depending on your timezone. If it's still on 1.11.2 or 1.10.2, then until @WesCook allows it (I want to update Animania support on 1.11.2 and 1.10.2 once their next build hits, as they are planning some major things, and yet they are dependency-locked until Craftstudio API updates), I can't do much.

**Comment by TheLimePixel** [comment]
I actually wanted to suggest it for the 1.12 version. Here: https://minecraft.curseforge.com/projects/primalcore

**Comment by Sunconure11** [comment]
Alright, I'll attempt it soon, though since there are plans for a move, I might not be able to get around to it. Couple that with the fact I'm trying to set up recipes on my mod now that I ported to 1.12, and I don't have much time.

**Comment by Sunconure11** [comment]
I'm on it. I had some issues trying to figure out the JSON recipe system, but I've got it under control now.

**Comment by WesCook** [comment]
As per #23, PrimalCore support is now in [v2.3.0](https://github.com/WesCook/Nutrition/releases/tag/v2.3.0).
