### ISSUE TITLE
Suggestion - Why not add "real" penalties?

### ISSUE THREAD

**Issue by MrPerruche** [WesCook/Nutrition#201]
When I tested the mod, I decided to put all the bars at 0%. However, it was absolutely not what I expected to have. In reality, people die because they don't eat protein or vegetables. While in the mod, If we have everything at 0% we only have some slightly disturbing effects, but not more than that. So I think it would be good to settle this and be able to at least not necessarily die but be kept at all times at 2 Hearts, 3.5 max. I'm not saying who should mix really annoying effects like nausea, but more realistic effects. _If you have no ideas here are some:
  - Smell the maximum life (For example go from 10 hearts max to 8 hearts max)
  - Give damage
  - Give mining fatigue, weakness ...
  - (Maybe) Give slowness etc._
_(Sorry if you not understand I used google translate ...)_

**Comment by WesCook** [comment]
Hi Perruchy,

Thanks for your suggestion.  Nutrition is designed to be fully configurable, so effects can already be completely customized.  If you want to enable slowness under 20% nutrition, you can do that.  Please see the wiki tab above for more info on how to customize things.

Nutrition effects are based on potion effects, so some things like reducing health aren't possible out of the gate.  It is possible to use potions from other mods though, so you have quite a few options to work with in a larger pack.
