### ISSUE TITLE
tips

### ISSUE THREAD

**Issue by EnterFor** [WesCook/Nutrition#203]
I would like to request the addition of instructions to view player nutrition
And give the player nutritional value
Don't you know it can be done?
Sorry, my English is not good. I'm Chinese

**Comment by WesCook** [comment]
I'm unclear on the request.  However, nutrition levels can be viewed using the nutrition GUI.  This is activated via the carrot icon, or [N] key on the keyboard.  If you're asking for a way to inform the user that nutrition exists, I'd suggest including it in a quest book or similar format.

Nutrition can be assigned programmatically using chat commands.
https://github.com/WesCook/Nutrition/wiki/Chat-Commands

Does that answer your questions?

**Comment by EnterFor** [comment]
Thank you. That's what I'm looking for
