### ISSUE TITLE
How to add item to dairy list

### ISSUE THREAD

**Issue by MilitaryFool** [WesCook/Nutrition#208]
I'm having a problem with adding another mod's dairy bottle to the nutrients list. This comes from the mod bottled milk. I added the item name into the space with the rest of the items but it wont act the same, what more do I need to do?

**Comment by WesCook** [comment]
The most likely answer is that the milk items are not of type `ItemFood`.  That means they do not have a standard food value associated which can be read by Nutrition.

I checked the page on Curseforge to verify, but they do not link to the source code.  So I can only guess as to the cause.  If you turn on the logging features in the config file you may be able to learn a little bit more.

**Comment by MilitaryFool** [comment]
Thank you this is very helpful, have a nice day.
