### ISSUE TITLE
[Suggestion] Advancement Support

### ISSUE THREAD

**Issue by whizzball1** [WesCook/Nutrition#21]
What if certain "food groups" could be activated upon reaching an advancement? (Note that custom advancements can be built into worlds by other mods.) I believe this could be useful for modpack makers--for example, if they want to allow a certain nutrition bar with its effects to become available after the player has reached a certain stage, perhaps one that enables automation of a certain food.

**Comment by WesCook** [comment]
Thanks for the suggestion.  I've never actually used the advancement system before (or played with 1.12 at all outside of this port), so I'll need to learn more about how they work.

The second factor is how ready they are to be used in Forge.  If that code is still early and obfuscated, I'd rather wait for things to stabilize a bit before building on that system.

So no promises on this one, but I will check it out.  Just know it may require some time to mature, or ultimately may just not fit my vision for the mod.

**Comment by WesCook** [comment]
Hey whizzball,

Unfortunately I've decided that locking nutrients behind Advancements would introduce too much complexity to the mod at this time.  I understand how this could be useful for modpack authors, but so far advancements don't seem to be the main method modpacks are using for gating progress at this time.

It's something I may reconsider in the future if I think it would get more use, but I don't consider the added complexity to be worth it at this time.

Thanks for your suggestion though.
