### ISSUE TITLE
Please read

### ISSUE THREAD

**Issue by Kyl1annCompany** [WesCook/Nutrition#210]
The site https://aternos.org to create its server does not accept mods not coming from curseforge, can you please persuade them to accept your mod on their site.
To send a proposal, go to https://board.aternos.org

**Comment by WesCook** [comment]
I'm sorry, but I'm not going to sign up to a message board for a server host.  The mod is licensed as MIT so they have full permission to host the mod files.  It is also on Curse's "third-party mod list" if that satisfies their requirements.

**Comment by Kyl1annCompany** [comment]
oh okay
