### ISSUE TITLE
Chinjufu support?

### ISSUE THREAD

**Issue by Mordunce** [WesCook/Nutrition#211]
I was just curious to see if it would be possible to add chinjufu support.

https://www.curseforge.com/minecraft/mc-mods/chinjufumod

**Comment by WesCook** [comment]
I likely won't be adding new mod support for a little while, but I'll leave this request up until I can take a closer look at it.

**Comment by Mordunce** [comment]
Thank you!

**Comment by WesCook** [comment]
It took a while, but this was included in [v4.8.0](https://github.com/WesCook/Nutrition/releases/tag/v4.8.0).

**Comment by Mordunce** [comment]
Alright, thanks again!
