### ISSUE TITLE
Support for Twitch Mod Pack?

### ISSUE THREAD

**Issue by Mr-Ian** [WesCook/Nutrition#213]
I'm trying to build a Mod Pack using Twitch, I can't find your Mod on there, what should I do?

**Comment by WesCook** [comment]
You would add it as a third-party mod.  I expect you could just drop it in the `Overrides/mods` folder.

https://help.twitch.tv/s/article/guide-to-modpacks?language=en_US

I'm going to close this as it's not related to the mod.
