### ISSUE TITLE
Heat and climate mod support?

### ISSUE THREAD

**Issue by tsukaerujuriki2** [WesCook/Nutrition#214]
would it be possible to add support for  [heatandclimate](https://www.curseforge.com/minecraft/mc-mods/heat-and-climate)

**Comment by WesCook** [comment]
Last I checked, Heat and Climate was supported.  Is it no longer functional?

Note that not all items may work.  Particularly if they're complex or require NBT data.

**Comment by tsukaerujuriki2** [comment]
Sorry I somehow missed it at the read.me

**Comment by gatoborrachon** [comment]
well, i think that Heat&Climate have had many new meals over this time, but yeah there are a lot of items that use Metadata
