### ISSUE TITLE
[Mod Support] Vampirism

### ISSUE THREAD

**Issue by EarendilTurambar** [WesCook/Nutrition#220]
Hello! This is a great mod, I love how it supports so many mods.
I wonder if you can add compatibility with the maxainer's Vampirism mod: https://www.curseforge.com/minecraft/mc-mods/vampirism-become-a-vampire 
For now the nutrition button in the inventory overlaps with the vampirism button. And it seems to me that the nutrition keeps going down while you're a vampire. If you could add that compatibility I would really appreciate it!
Sorry if I wrote something wrong, English is not my native language.

**Comment by WesCook** [comment]
Hi Earendil,

>For now the nutrition button in the inventory overlaps with the vampirism button.

You can adjust the X and Y coordinates of the button through Nutrition's configs.  I set the default position based on vanilla, but you'll need to make changes if there's a conflict with other mods.

>And it seems to me that the nutrition keeps going down while you're a vampire.

If Vampirism constantly drains the player's hunger, this would be the effect.  Is that what's happening?  It's possible to disable this nutrition drain, but of course that would make the mod completely unbalanced.  You could also tweak the numbers (eg. halve the rate of decrease) to find a balance.

I don't think I'd want to add specific detection for if a player is a vampire, though.  While I don't mind fixing bugs or merging food support at this point, Nutrition is mostly in maintenance mode on 1.12.  I've also tried to keep the mod integrations to config files, which wouldn't really be possible here.

I'm not actually familiar with the Vampirism.  Would this behaviour be considered game-breaking, or is it more of a tradeoff?  In terms of lore becoming malnourished by taking on an all-blood diet at least makes some sense.

**Comment by EarendilTurambar** [comment]
> You can adjust the X and Y coordinates of the button through Nutrition's configs. I set the default position based on vanilla, but you'll need to make changes if there's a conflict with other mods.

Thanks for implementing this in your mod! I used the mod "No Recipe Book" and moved the Nutrition's button to that position changing the number 134 of the x-axis by 100.

> And it seems to me that the nutrition keeps going down while you're a vampire.

And this was my mistake! My character died and the nutrition values were reestablished, so I thought they were going down even as a vampire. But when you're a vampire those values hold steady, which is exactly what I wanted.

Thanks for the help! And good job for the mod!

**Comment by WesCook** [comment]
Glad to hear it.  In that case I'll go ahead and close this issue.
