### ISSUE TITLE
[1.12.2] Could you add support for Oh the Biome's You'll Go?

### ISSUE THREAD

**Issue by vizthex123** [WesCook/Nutrition#222]
Also, it would be interesting if Rotten Flesh remove a few points from each nutrient.

(Also can you pluralize all of the nutrients in the GUI?)

I've added BYG foods to the configs (should be correct in terms of what food contains what):

[JSONFiles.zip](https://github.com/WesCook/Nutrition/files/5732824/JSONFiles.zip)

**Comment by WesCook** [comment]
>Also, it would be interesting if Rotten Flesh remove a few points from each nutrient.

Essentially it does.  It triggers the hunger effect which depletes nutrition automatically.

>Also can you pluralize all of the nutrients in the GUI?

I prefer it as-is, but you can change the language file for yourself.
https://github.com/WesCook/Nutrition/blob/1.12/src/main/resources/assets/nutrition/lang/en_us.lang#L9-L14

>I've added BYG foods to the configs

Thank you.  I'm not currently doing maintenance on the mod, but will review this when I next add new mod support.

**Comment by vizthex123** [comment]
Alright, thanks. And yeah I forgot it does that. Could you make it be blacklisted from the missing nutrients scan? (that's how I found out about it). Same for Spider Eyes.

And I thought I could with the .json configs, but it doesn't render properly (just says like `nutrition.nutrients.whatever.` Maybe you could add it as a config option or something?

**Comment by WesCook** [comment]
The JSON refers to the language key.  You need to update the lang file as linked above.  For English the file would be `en_us.lang`.  This can be overwritten via Resource Packs (for local play), or a mod like [Resource Loader](hhttps://minecraft.curseforge.com/projects/resource-loader) for packs.

I don't plan to blacklist anything from the log functions as they're just there for debugging.

**Comment by vizthex123** [comment]
I went ahead and made a pull request for it: #246

**Comment by WesCook** [comment]
Included with the newly-released [v4.8.0](https://github.com/WesCook/Nutrition/releases/tag/v4.8.0).  Thanks for the PR.

**Comment by vizthex123** [comment]
noice, thanks.
