### ISSUE TITLE
[Update Support]Heat and climate mod

### ISSUE THREAD

**Issue by Gonbuto** [WesCook/Nutrition#227]
https://www.curseforge.com/minecraft/mc-mods/heat-and-climate
Would you update support for Heat and Climate Mod?

**Comment by WesCook** [comment]
Previously discussed in #214.  If there's new items that can be added, I'll leave this issue open.

**Comment by Gonbuto** [comment]
Thank you!

**Comment by WesCook** [comment]
I've added all the new foods in [v4.8.0](https://github.com/WesCook/Nutrition/releases/tag/v4.8.0).
