### ISSUE TITLE
Please explain nutrition decay mechanics

### ISSUE THREAD

**Issue by Nevarre750** [WesCook/Nutrition#230]
I'm having difficulty understanding the mechanics behind the nutrition decay. What causes nutrition values to decrease? Is it time or when "hunger" is decreased? How does the math work for the decay multiplier? If the "EnableDecay" setting is false, will nutrition values ever decrease?

**Comment by WesCook** [comment]
>What causes nutrition values to decrease?  Is it time or when "hunger" is decreased?

It's specifically when hunger drumsticks decrease.  Time is not a factor, nor is saturation.

An early working version used time but I felt using hunger drain would be more auto-balancing.  No need to worry about nutrition unless you're burning calories.  Plus I didn't want to punish players who AFK.

>How does the math work for the decay multiplier?

It's a straight multiplier.  A value of 2 will decay twice as fast.  0.5 will halve the rate.  Negative numbers are also possible, if you want decay to increase nutrition for some reason.

I take the difference in food level from the previous tick, normalize it to set a standard decay rate, then apply the multiplier.  You can [see the code here](https://github.com/WesCook/Nutrition/blob/9ccf2174e92f37be6990ff210b4118b37adbc32a/src/main/java/ca/wescook/nutrition/events/EventWorldTick.java#L85-L91).

>If the "EnableDecay" setting is false, will nutrition values ever decrease?

Only via death, assuming `DeathPenaltyLoss` is set.
