### ISSUE TITLE
Post to CurseForge?

### ISSUE THREAD

**Issue by MagmaSlime123** [WesCook/Nutrition#232]
https://www.curseforge.com/minecraft/

**Comment by WesCook** [comment]
Previously answered in #172.

**Comment by MagmaSlime123** [comment]
You might as well just talk with CurseForge about this then. The Technic Platform is similar to Curse but more about modpacks.

**Comment by WesCook** [comment]
I have no plans to add to CurseForge.  The mod is licensed under MIT and available on their third-party mod list, so it can be added freely to any modpacks.
