### ISSUE TITLE
JAFFA Mod Support

### ISSUE THREAD

**Issue by MagmaSlime123** [WesCook/Nutrition#234]

**Comment by WesCook** [comment]
Pam's HarvestCraft is already supported.  JAFFA is a possibility, but I'll need to revisit it during the next mod update.

**Comment by WesCook** [comment]
This has been added in [v4.8.0](https://github.com/WesCook/Nutrition/releases/tag/v4.8.0).

**Comment by MagmaSlime123** [comment]
Cool.
