### ISSUE TITLE
Food Funk Compat?

### ISSUE THREAD

**Issue by MagmaSlime123** [WesCook/Nutrition#236]
Food Funck basically adds the ability for foods to rot and spoil over time. Nutrition could be linked to this so the more rotted a food item is, the less nutricis (Can't spell) it is as well. There are ways to keep foods from rotting as well, such as Freezer Chests.

Rotten Food could probably cause your Nutrition to decrease a lot, but I'm not sure.

![2021-04-27_10 01 25](https://user-images.githubusercontent.com/51277766/116273979-160e2e00-a737-11eb-95d2-f94e5e6c2887.png)

**Comment by WesCook** [comment]
I believe this mod has been discussed before.  The hope was it would be addressable with the mod API, but that project never came to be.

Nutrition does automatically adjust nutritional-gain based on hunger value restored (ie. the "honches").  If Food Funk adjusts these honches, then nutritional-gain will reflect that as well.

If the idea is that nutritional-gain should be lower than hunger value gained, to decrease the overall value of the food, then that makes sense but isn't currently possible at this time.

While I'm not planning on adding any new features at this time, I would be open to the idea if I began developing the mod actively again.  However as it's not within the current scope of development, I'll mark this issue as closed.
