### ISSUE TITLE
"detect": "average" issue

### ISSUE THREAD

**Issue by randemail** [WesCook/Nutrition#237]
When using "detect": "average", the mod is not using the nutrients I whitelisted.
(I'm adding secret nutrients in my private pack so it causes some problems like getting mining fatigue at 32% average instead of 20.)

I decided to look at the code and I think it's adding all nutrients in the whitelist to the total but then it divides it to all nutrients that exist.

This is my favorite mod btw, thank you for making it.

**Comment by WesCook** [comment]
Great report.  You were right about the cause of the issue.  I've fixed that now and just [pushed a new release](https://github.com/WesCook/Nutrition/releases/tag/v4.7.0).  Give it a try and let me know if that solves the problem for you.

I'm glad you're making good use of the mod.  Thanks for the report!

**Comment by randemail** [comment]
That solved it!
Thanks!
