### ISSUE TITLE
[Suggestion] Allow negative values for where to place the Nutrition button

### ISSUE THREAD

**Issue by quat1024** [WesCook/Nutrition#24]
I want to put it up here, basically: 
![image](https://user-images.githubusercontent.com/2068021/29051965-878583ec-7bb4-11e7-81b9-7a2b5624b357.png)

but can't move it any farther to the left, because the minimum value for the X and Y position of the button is 0 :(

**Comment by WesCook** [comment]
No problem, that should be an easy fix.  I'll include this in the next version.

**Comment by WesCook** [comment]
This has been added in [v2.3.0](https://github.com/WesCook/Nutrition/releases/tag/v2.3.0).  Sorry for the delay, but I had some other features related to the button positioning I wanted to support as well.

Specifically, it's now possible to set the button position relative to either the screen or the inventory GUI, and to also choose a side to "anchor" to.

So for instance, the default position is anchored to the `top-left` of the gui, with an offset applied to move the button beside the recipe book.

You could instead move it towards the `top-right` of the screen if you wanted, so it's set independently of the player gui.

Hopefully this should allow enough customization for anybody's needs.
