### ISSUE TITLE
Nutrition is screwed in Curseforge packs

### ISSUE THREAD

**Issue by Sunconure11** [WesCook/Nutrition#240]
Because someone had uploaded Nutrition on Curseforge in the past, updating packs with Nutrition is a bit trickier, especially when new things have been added, codewise.

https://www.curseforge.com/members/jamesdamaker/projects

This was the user who had nutrition on curseforge for a bit.

**Comment by Sunconure11** [comment]
Proof of my claim, as found in an instance of a curse pack that has nutrition:

![image](https://user-images.githubusercontent.com/5614902/121044566-8f139300-c783-11eb-8874-e9873761b9d4.png)

**Comment by WesCook** [comment]
Thanks for the report.  I was afraid that might happen.  Curseforge seems to have a system that prevents uploads when they think they host the file.  It happened once in 2020 (see #218), and presumably this occurred again due to the events of #239.

I see you already pinged James, so we'll see if he can further remove the project from his profile.  If not, I'm afraid we'll need to contact Curseforge and ask them to fix it manually.

**Comment by samedifferent** [comment]
> Because someone had uploaded Nutrition on Curseforge in the past, updating packs with Nutrition is a bit trickier, especially when new things have been added, codewise.
> 
> https://www.curseforge.com/members/jamesdamaker/projects
> 
> This was the user who had nutrition on curseforge for a bit.

Hi Sunconure,

I've been trying to reach out to you about an old abandoned mod that you were involved in. I sent you a DM on curseforge about it. I would appreciate it if you could respond and give me any info you know about the matter. Thanks!

**Comment by Sunconure11** [comment]
@WesCook I think you might want to contact Curse

**Comment by WesCook** [comment]
While they offered no traditional support channels, I was able to report the issue via their Discord server.  A community admin said it would take approximately 15-24 hours (from the time of this message) to be processed.

If it's still not working in a day or two, please let me know and I'll follow up.

**Comment by Sunconure11** [comment]
Alright.

**Comment by WesCook** [comment]
I've received an update from Overwolf.  They said that while the project had been deleted, the mod files had not been.  They've gone ahead and deleted those which should have resolved the issue.

Can you test again please, @Sunconure11?  Thank you.

**Comment by Sunconure11** [comment]
I can confirm it works.
