### ISSUE TITLE
Mod not in Curseforge

### ISSUE THREAD

**Issue by Vasco2020E** [WesCook/Nutrition#241]
Soo i wanted to add this mod to my server but cince i use aternos then i can't add it because it's not in the Curseforge website is it possible to add it?

**Comment by WesCook** [comment]
Please see #172.

**Comment by Vasco2020E** [comment]
Soo you're waiting your mod to be approved?

**Comment by WesCook** [comment]
No, I've elected not to add the mod to CurseForge.  The reasons are explained in the linked issue above.
