### ISSUE TITLE
curse forge

### ISSUE THREAD

**Issue by BlazeGaminginit** [WesCook/Nutrition#242]
Is this mod going to be out to download in curse forge, cuz I would like to add this to my RLCraft server and the server luncher that i'm using is Aternos and they won't accept any mods that are downloadable outsaid of curse forge. 

It's fine if not

**Comment by WesCook** [comment]
I don't have any plans to release on CurseForge.  See #172 for further details.

If Aternos doesn't support the third-party Curse modlist, or direct jar uploads, you may need to request they lift that limitation of their platform.
