### ISSUE TITLE
Uploaded to CF without authorization

### ISSUE THREAD

**Issue by brisingraerowing** [WesCook/Nutrition#244]
[CF Page by another person](https://www.curseforge.com/minecraft/mc-mods/nutrition-mod)

From what you mentioned in another issue, you don't want this mod on CF.

**Comment by WesCook** [comment]
Thank you for letting me know.

**Comment by WesCook** [comment]
The page has been removed now, so I'll go ahead and close this issue.  Thanks again for letting me know.
