### ISSUE TITLE
Porting to newer version

### ISSUE THREAD

**Issue by UnluckyChicken** [WesCook/Nutrition#245]
So i found ur mod in a modpack a bit ago, yesterday i made a new survival world in 1.16.5. I tried to add ur mod but it's only for 1.12.2. Do you plan on putting the mod on more recent versions of Minecraft or are you not? I'm sorry if you get asked this a lot but i just generally wanna know, thanks.

**Comment by vizthex123** [comment]
This mod does the same thing for 1.16.5, and handles it a bit better: https://www.curseforge.com/minecraft/mc-mods/diet

(At minimum, I think the UIs look *much* nicer).

If you know how to program in Java, you can probably make a [pull request](https://github.com/WesCook/Nutrition/pulls) for it too.

**Comment by WesCook** [comment]
I'm sorry, but there's no plans to port to a new version at this time.  I recommended some alternatives on 1.16 [in this post](https://github.com/WesCook/Nutrition/issues/207#issuecomment-867353042).
