### ISSUE TITLE
CI/CD to Curseforge? (and github ofc)

### ISSUE THREAD

**Issue by Macleykun** [WesCook/Nutrition#250]
I've made a CI/CD over at Future-MC:
https://github.com/thedarkcolour/Future-MC/blob/main/.github/workflows/autobuilds.yml

If you want, i can make the same for you. Ofcours i'll tweak it more to what you normally make here (like correct tagging instead of always using latest).

What you think? Would having a full CI/CD for each branch (or only your active if you want) be something to reconsider Curseforge? Tottaly understand if you decline!

**Comment by WesCook** [comment]
Hi Macley,

Thanks for your generous offer.  I'm not looking to upload to CurseForge at this time (for reasons I [touch on here](https://github.com/WesCook/Nutrition/issues/172#issuecomment-507827779)), so I will be declining.  However, I do appreciate your willingness to streamline the process for me.  That's very kind.

If circumstances ever change, I'll reconsider the offer at that time.  Thank you.

**Comment by Macleykun** [comment]
np! already read that post so it's tottaly cool :) enjoy the new year!
