### ISSUE TITLE
Yet another unauthorized post of this mod.

### ISSUE THREAD

**Issue by MagmaSlime123** [WesCook/Nutrition#253]
https://www.curseforge.com/minecraft/mc-mods/foods-nutrition.

**Comment by WesCook** [comment]
Thanks for the report.  Though this is what I'm seeing:

> Not found
> We were unable to find the page or file you were looking for.

Has it been taken down already?

**Comment by MagmaSlime123** [comment]
I think, but Curse is very slow.

![image](https://user-images.githubusercontent.com/51277766/168277758-f813e49f-2b19-4a67-a9ec-8ced4c783821.png)
