### ISSUE TITLE
Posted to Curse without permission. Again...

### ISSUE THREAD

**Issue by MagmaSlime123** [WesCook/Nutrition#255]
Title.

https://www.curseforge.com/minecraft/mc-mods/foods-nutrition

**Comment by WesCook** [comment]
Thanks for the heads up.  The mod appears to be unlisted.  Was it perhaps already removed?

**Comment by MagmaSlime123** [comment]
No clue. Posted here anyways, just in case.

**Comment by WesCook** [comment]
It seems to be the same project URL as #253, so I'm assuming it's the same one.  If it's showing up in the client but not the web, that could indicate the project still exists, but is set to hidden/private.

**Comment by MagmaSlime123** [comment]
Ah. Idk how to report it then, since no report function exists within the CF app.

**Comment by freopt** [comment]
should probably change the license if you don't want reposts
