### ISSUE TITLE
[Question] How does the mod decide how the various nutrient bars degrade?

### ISSUE THREAD

**Issue by DragonJak** [WesCook/Nutrition#256]
I'm currently playing Sevtech: Ages of the Sky [3.2.3]. I have a Mantle of Stars (Aevitas) that automatically replenishes health. food, and saturation. However, it doesn't look like this auto-feed mechanic applies any nutrient points to any of the four bars. So while I will be replenishing hunger at a steady rate, I'm worried the bars will slide back down and I'll lose my bonus maximum health.

So I wanted to ask, do the sliders tick down at a constant rate, or do they only tick down when you are low on food/saturation?

**Comment by WesCook** [comment]
They tick down specifically when you lose food (drumsticks), but not saturation.  If the effect keeps you topped up, then you shouldn't experience any decay except from death.  You may have a difficult time eating to increase your listed nutrition further though.

#230 has a little more information.
