### ISSUE TITLE
Add compatibility for RealWorld (I made a list)

### ISSUE THREAD

**Issue by ghost** [WesCook/Nutrition#26]
Add compatibility for [RealWorld ](http://10paksmods.net/)foods. I made a [list here](https://pastebin.com/rzKUJy3J).

**Comment by renadi** [comment]
Not relevant, but thank you for making me aware of this mod, I'm incredibly
interested in it right now!

**Comment by ghost** [comment]
@renadi your welcome :)

**Comment by WesCook** [comment]
Much thanks for the contribution.  There were a lot of difficult classifications in this batch.  eg. Legumes which act as both a grain and protein.  I made a few tweaks to improve consistency, but kept most entries.

This will be in the next release.

**Comment by WesCook** [comment]
Thanks again.  I've added RealWorld support in [v2.3.0](https://github.com/WesCook/Nutrition/releases/tag/v2.3.0).
