### ISSUE TITLE
[Suggestion] Consider special-casing milk buckets

### ISSUE THREAD

**Issue by WesCook** [WesCook/Nutrition#29]
Dairy is currently lacking many food sources in vanilla Minecraft.  Milk buckets are logical, however aren't a regular food item and so aren't supported.

Not all modpacks may include dairy, so hardcoding milk buckets to increase dairy is a bad idea.  However, I could instead look for `milk_bucket` as a food item and offer a small hunger value in the listed nutrient instead.

**Upside:** More intuitive behavior that milk restores dairy.
**Downsides:** More hardcoding; drinking milk isn't particularly interesting.

Previous discussion of milk support was discussed in #5.

**Comment by WesCook** [comment]
Support has been added in [v2.4.0](https://github.com/WesCook/Nutrition/releases/tag/v2.4.0).

**Comment by KnightMiner** [comment]
How difficult would it be for me to add support to use my clay milk bucket as well? It is not ItemBucketMilk as I use one bucket item for all liquids, but can still be consumed normally, so maybe a way for me to tell Nutrition in my mod it's a food?

**Comment by WesCook** [comment]
Currently that wouldn't be possible.  The provided list only supports IDs with metadata, but not NBT data.  I also don't have an API in place for mods to let Nutrition know about new foods directly, other than just using the json files.

I've not created an API in Forge before, so that currently exceeds my abilities.  I'd also need to loosen some assumptions about what kinds of foods are acceptable (probably let mods supply an optional nutrition value, rather than reading it directly from the ItemFood).

Another thought I had was to allow CraftTweaker support to override specific food values, and to allow assignment programmatically.  But that too exceeds my current abilities.

**Comment by KnightMiner** [comment]
I do use metadata to distinguish my milk just as a milk fluid does not always exist, so that should make it a bit easier.

I feel like an override API would be ideal with a fallback to itemfood, as then some of the more unusual foods from other mods could be added too. Ideally it would just be a arraylist or hashmap of food and Nutrition values, and can be filled with direct register  methods or IMC support, I can look into this when I have time if you wish

**Comment by WesCook** [comment]
>I feel like an override API would be ideal with a fallback to itemfood

Yeah, I was thinking about this.  An override would be the simplest approach.  Or it might be a good idea to refactor it to a single master list instead, and always check that rather than determining food values on the fly.  That would be cleaner because it means less instanceof checking later in the code.  I could at least keep all the hacks in one place then.

Right now I'm only looking at two events: `PlayerInteractEvent.RightClickBlock` (cakes) and `LivingEntityUseItemEvent.Finish` (ItemFood/ItemBucketMilk).  Would that cover most use cases for unusual foods, like your milk buckets?

>... and can be filled with direct register methods or IMC support, I can look into this when I have time if you wish

Sure, I'm open to the idea.  Though some cleanup, as described above, would probably be needed in advance.

**Comment by KnightMiner** [comment]
Should cover most foods, I use onItemFinishUse for the milk actions (basically the same code as normal milk buckets) .
