### ISSUE TITLE
[Integration] Actually Additions, Ender IO, and Extra Utilities 2

### ISSUE THREAD

**Issue by ghost** [WesCook/Nutrition#31]
Actually Additions: https://pastebin.com/yUxMpjEQ
Ender IO: https://pastebin.com/bA74Qyev
Extra Utilities 2: https://pastebin.com/CFNfbinj

**Comment by WesCook** [comment]
Thanks for the contribution, Ethan.  I've included support for Actually Additions and Extra Utilities in the [just released version](https://github.com/WesCook/Nutrition/releases/tag/v2.4.0).  Unfortunately Ender IO hasn't been updated to 1.12 yet, and I'm not supporting older versions, so it can't be included.

I'm glad I didn't need to figure out those Actually Additions jams myself.
