### ISSUE TITLE
[2.4.0] MC Version check intended or an oversight?

### ISSUE THREAD

**Issue by ghost** [WesCook/Nutrition#34]
Version 2.4.0 specifically asks for MC 1.12.2. Does it not work with 1.12 & 1.12.1?

**Comment by WesCook** [comment]
I targeted Forge 1.12.2 for this release, but didn't consider that it would also exclude earlier versions.  I'll specify support for all Forge 1.12.* versions in the next release.

You'd probably have better luck moving to a 1.12.2 environment though, and seeing if any 1.12.1 mods are incompatible.  I expect it should just work out of the box.

**Comment by ghost** [comment]
I suspect so as well, just haven't had the time yet to convert. np.

**Comment by WesCook** [comment]
I pushed a [small update](https://github.com/WesCook/Nutrition/releases/tag/v2.4.1) just to address this.  Should now work on any 1.12 version.
