### ISSUE TITLE
Investigate refactoring of nutrition lookup

### ISSUE THREAD

**Issue by WesCook** [WesCook/Nutrition#35]
Consider building a list of nutrients on game start, rather than looking it up on the fly.  This list could then be modified more easily by an API, as discussed in #29.

Alternatively, an override list with fallback to live lookup may reduce complexity.

**Comment by Sunconure11** [comment]
You might want to add support for things like milk bottles from Endless Traverse, as well.

**Comment by WesCook** [comment]
If creating an override list, consider storing both associated nutrients and nutritional value so this can be specified independently of hunger value.  Specifying value per nutrient may be adding too much complexity, though.

**Comment by TheElemento158** [comment]
In #29 you mentioned adding CraftTweaker support for the mod, I'm not sure if it's as simple as what I'm about to suggest, but wouldn't that only need a recipe handler? 

If a recipe handler was made that is able to take an item, apply nutrients in first startup, in this case the five in the mod by default, through use of the current default configs, and output what foods were added into each nutrient to a list, it might work. 

If the current nutrients were in the handler as "nutrientDairy", "nutrientVeggie", "nutrientGrain", "nutrientProtein", and "nutrientFruit", it shouldn't be *too* difficult for the handler to accept "nutrient_____" as an accepted format for new, (disabled by default) nutrients added by mods like "nutrientSalt". If done in the right way, it might even allow for customization of nutritional values through the lists generated.

It would also have the bonus effect of having the potential to see how many nutrients there are in JEI, and how much different foods give. Helps to avoid super long tooltips when people (like me) use mods for food that triple the size of the tooltip all together.

This is just me thinking in my head though, I have extremely limited expertise when it comes to making a recipe handler for a new mechanic. The only thing with this idea though, is that I don't know how eating cake blocks would work. Also I don't know if this is actually how Nutrition works already as I don't know how to read that through the code.

Another idea I have is somehow allowing other mods to overwrite or add to the configs somehow, but I don't know how well that would work or if it would work at all

**Comment by TheElemento158** [comment]
Another idea is a calculation system similar to Equivalent Exchange/ProjectE's EMC system. 

You or a modpack creator could set nutrient groups and values for ingredients, and have a calculation for more and more complex foods. If having static calculations isn't what you want, have a formula option in the config similar to what Spice of Life does with it's hunger calculation.

**Comment by WesCook** [comment]
@TheElemento158: I'm not entirely sure what you're saying in your first comment, but allowing mods to set nutrients via IMC was definitely a consideration behind the override list mentioned above.

For your second comment, I thought about building nutritional value dynamically by looking at recipe parents, but it was too complex for me to tackle at the time.  There's still a lot of problems that I'd need to solve like avoiding recursive recipes, understanding other crafting handlers, and doing this in a performant matter, consistently on both client and server.

If that were to happen, it would likely be called Nutrition 2.  But that won't be for quite some time.
