### ISSUE TITLE
[Suggestion] Give Water Bottles a foodValue

### ISSUE THREAD

**Issue by phistoh** [WesCook/Nutrition#39]
I think it would be a nice addition if default _water bottles_ (and maybe all other potions?) had a small `foodValue`. Then it would be possible to implement a "basic thirst system" using the customizable "nutrients system" without relying on other mods.

(I don't know if this suggestion fits your creative vision for the mod, but a suggestion doesn't hurt anyone.)

**Comment by WesCook** [comment]
Currently this isn't possible with the way that food is registered (water bottles/potions use NBT data).  However there is a pull request that offers similar functionality, #38.

In terms of nutritional value though, water doesn't necessarily fit any of the default food groups so I probably wouldn't include it by default.  At some point I would like a way to offer NBT support though.  That may need to happen through CraftTweaker support, or through IMC though.

**Comment by phistoh** [comment]
Yeah, since your mod is about food, drinking doesn't really fit into the default configuration. I'll look into the pull request!

Thanks for your answer. :)

**Comment by WesCook** [comment]
As adding NBT support is still a long ways off, I'm going to mark this one as closed for now.  It's something I've been thinking about for a while, but would need to tie into a rather large refactor.  I'll have a more dedicated issue set up for that when/if that happens.
