### ISSUE TITLE
Crash with Hunger Overhaul and Better With Mods [1.10.2]

### ISSUE THREAD

**Issue by AntiDruid** [WesCook/Nutrition#4]
Done when you eat anything.
Maybe it's because it's incompatible with the "well-fed' effect but idk.

Crash log: https://pastebin.com/q1jE17VL

**Comment by WesCook** [comment]
Hrmm, I'm not able to reproduce this.  Can you test it with just Nutrition, Hunger Overhaul, and AppleCore installed?  Be sure to use a fresh world, or backup your real world first.

I'd like to know if it's a conflict with an additional mod, or a change in configs causing this.

**Comment by AntiDruid** [comment]
OK so Hunger Overhaul and Better With Mods work by themselves but when they are together w/ Nutrition, anything you eat = crash it seems

New crash log: https://pastebin.com/DFng1jgz

**Comment by WesCook** [comment]
Thanks for the update.  I'm able to replicate the crash now.

It looks like this is actually a conflict between BWM's Hardcore Hunger setting, and Hunger Overhaul.  Removing Nutrition doesn't affect the crash, so it's not on my end.

Normally I'd suggest reporting it to their issue trackers, but I think in this case it's a known conflict already.  In the mean time, I'd suggest disabling BWM's Hardcore Hunger setting if you want to use both mods together.

**Comment by AntiDruid** [comment]
Cool thanks
