### ISSUE TITLE
Can you please add support for these mods?

### ISSUE THREAD

**Issue by ghost** [WesCook/Nutrition#42]
Could you please add support for the following mods?

1. [Skye’s Donuts](https://minecraft.curseforge.com/projects/skyes-donuts)
2. [Grim Pack](https://minecraft.curseforge.com/projects/grim-pack)
3. [Immersive HempCraft](https://minecraft.curseforge.com/projects/immersive-hempcraft)
4. [Immersive Foods](https://minecraft.curseforge.com/projects/immersive-foods)
5. [Bobo’s Supermarket Mod](https://minecraft.curseforge.com/projects/bobos-supermarket)
6. [Simple Corn](https://minecraft.curseforge.com/projects/simple-corn)
7. [Duck Craft](https://minecraft.curseforge.com/projects/duck-craft)

That would be great!

I love the mod, by the way! It’s ten times better than The Spice of Life.

**Comment by Sunconure11** [comment]
Grim Pack support was on 1.11.2 IIRC

**Comment by ghost** [comment]
@Sunconure11 Not 1.12.2, though.

**Comment by WesCook** [comment]
That's a lot of requests.  I can add support to those which are popular enough to warrant it, or which have had support in the past and can be updated from a previous branch.

That would include Grim Pack, Simple Corn, and Duck Craft.  For the others I'm afraid they'd need to come from a pull request to be added.

**Comment by ghost** [comment]
Aw. Well, support for even just a few of these mods would be fantastic! I can’t live without Nutrition—literally!

[Skye’s Donuts](https://minecraft.curseforge.com/projects/skyes-donuts) is a great mod, though. It’s very polished and has 14.7K downloads. You should add support for that. Who’d pick corn over doughnuts?

**Comment by WesCook** [comment]
It looks like GrimPack and SimpleCorn are both already supported on 1.12.  I knew I'd added support for them before, but thought they must be on an older branch.

I'll see about adding support for the other two shortly.

**Comment by WesCook** [comment]
Many donuts from Skye's didn't actually have recipes, so there was some guesswork involved.  But support for it and Duck Craft have been added in [v2.6.0](https://github.com/WesCook/Nutrition/releases/tag/v2.6.0).

**Comment by ghost** [comment]
Thanks.

I did see that Grim Pack and Simple Corn were already on the list, but I thought you _just_ added them after reading my issue. Whoops.
