### ISSUE TITLE
[Idea] Configurable max health that scales with nutrition

### ISSUE THREAD

**Issue by ChiefLogan3010** [WesCook/Nutrition#45]
Really been enjoying your mod recently, I have one suggestion though; the ability to configure max health to nutrition levels, I think this would make players more immediately concerned with their diets than potion effects ever could.

**Comment by TheElemento158** [comment]
There are potion effects added by the mod that do that, if you go to the wiki section you can see them

**Comment by WesCook** [comment]
@TheElemento158 is correct.  Nutrition actually sets the Toughness potion effect by default, which does increase your health.  This can be adjusted through the config system, or made more granular by using the `nourished` [effect](https://github.com/WesCook/Nutrition/wiki/New-Potion-Effects) instead.

Does that address your concern?

**Comment by Jomik** [comment]
And, the other way, you can use `malnourished`.

@WesCook Those two effects are not used by default?

**Comment by WesCook** [comment]
Nope.  I just added them in case people wanted more granular control over health gain.

Vanilla does have a built in potion effect for health gain, but it resets your hearts every time it's reapplied.  So that made it pretty useless when used by Nutrition.

**Comment by WesCook** [comment]
I think this issue has been addressed, so I'm going to close this for now.  Thanks for the feedback!

**Comment by WesCook** [comment]
Just to update this issue, I've since adjusted the mal/nourished effects so they apply half-hearts instead of full hearts.  This grants more control over granularity, at the cost of requiring a change to amplifier levels.

This change is in [v3.0.0](https://github.com/WesCook/Nutrition/releases/tag/v3.0.0) (thus the updated major version number).
