### ISSUE TITLE
displaying wrong name and author on twitch launcher

### ISSUE THREAD

**Issue by majijn** [WesCook/Nutrition#48]
![givh](https://user-images.githubusercontent.com/18368034/36180083-3f2e5596-111f-11e8-8c8a-7ddaadd12b27.png)
I tried deleting it and redownloading it but it still displays this name, I dont know why twitch is doing this.

**Comment by WesCook** [comment]
Well that's odd.  None of that metadata is contained in the mod itself, so they're incorrectly pulling it from somewhere else.  It's something they'll need to fix on their end though.  I have a valid mcmod.info file, but they're choosing to ignore that data in favor of an in-house database.

Thanks for bringing it to my attention, but as it's not something I can change I'm going to close this.
