### ISSUE TITLE
[1.12.2] [Feature-Request] Add possibility to set custom nutrition value

### ISSUE THREAD

**Issue by Fireztonez** [WesCook/Nutrition#54]
Hello, 
I am currently developing a big modpack and I decided to add your mod to add a realistic side to the food and encourage to eat different things. A small thing that I think it would be really good to add, to give more flexibility and especially to help me manage the proper nutritional value of each food, would be to add the ability to configure the value nutritious for each group manually for each food.

**Comment by WesCook** [comment]
Hi Fireztonez,

Thanks for the request.  I've toyed with the idea of letting players set nutrition values for individual foods, but Nutrition really isn't set up to work in that way right now.  The config files are too simplistic, and I'd like to avoid adding that sort of complexity to them.

I've thought about adding CraftTweaker support to allow an override list that way, but currently that's not in the cards.  It may come at some point in the future.

So I'm afraid there's no current plans to implement this functionality.  Thanks for your suggestion, though.

**Comment by talonos2** [comment]
Would you be open to a pull request that adds this functionality?

I'd probably implement it by having another json file (empty by default) where you could define food "overrides". EventEatFood.applyNutrition (line 114ish) would first check to see if there's an override for that itemstack, and if so, call a different function that applies nutrition based on values specified in the override file.

Having the suggested functionality be based on an "Override" system would let you keep the simplicity of the config files, and let modpack makers makers easily assign nutrition to many foods at once while still allowing them to hard-config specific exceptions. (If a modpack maker wants to go nuts and apply overrides to everything, then that's their problem I guess.)

No promises of course, just asking before I start looking deeper into it and setting up a dev environment to tinker around in.

**Comment by WesCook** [comment]
Hi @talonos2,

Thanks for the offer.  Your suggestion of using an alternate json file for more advanced overrides is a good one.

Personally I was thinking of using an internal override list so it could be manipulated via IMC or CraftTweaker instead.  Your suggestion of using json is more accessible to modpack devs (no dependency on CraftTweaker), which is desirable.

The downsides though are that it can't be edited programmatically, and I'm a bit concerned that having nutrient-information defined in two locations might complicate the workflow for modpack devs.  Admittedly that might just be me grousing about change though.  I do recognize that this file would only be for advanced overrides.

It seems like the need for overriding nutrient values is there, as I've gotten a few requests for it now.  So I'd like to find some solution.

I'm still a bit undecided though.  Could you give an example of how the json might look for the new file?

I also wonder if a simplified format change could be introduced to the existing file for overrides, without damaging compatibility or creating too much confusion.

One idea is to embed it directly in the food item using some delimiter.

```json
"food": {
    "oredict": [],
    "items": [
        "vanillafoodpantry:snowcone:1|4.5"
    ],
}
```

Or alternatively to add a separate section for it:

```json
"food": {
    "oredict": [],
    "items": [],
    "override": {
        "vanillafoodpantry:snowcone:1": 4.5,
        "vanillafoodpantry:snowcone:2": 3.5
    }
}
```

or

```json
"food": {
    "oredict": [],
    "items": [],
    "override": [
        ["vanillafoodpantry:snowcone:1", 4.5],
        ["vanillafoodpantry:snowcone:2", 3.5]
    ]
}
```

Just spitballing.  Would be glad to hear any other thoughts on this.  I'd like to find the cleanest solution, if possible.

Also just a heads up, I'm expecting to be quite busy during the upcoming weeks so I may not have a chance to review+merge any changes during that time.  Thank you for understanding.
