### ISSUE TITLE
Accept decimal values for effect 'amplifier' and 'cumulative_modifier'

### ISSUE THREAD

**Issue by sharkykh** [WesCook/Nutrition#56]
Hi. 

Is there a way to make the 'amplifier' and 'cumulative_modifier' properties of an effect (such as [toughness](https://github.com/WesCook/Nutrition/blob/9e3e743a9a1b295ba9270aa56dea5bdfdaccbdc1/src/main/resources/assets/nutrition/configs/effects/toughness.json)) accept **decimal** values?

The use case is,
If you change the amount of nutrients, say you removed 'dairy', and you wanted each toughness effect level to add 2.5 hearts (5 "half-hearts") to the player instead of 2 (to still get a total of 10 (20) extra hearts), that requires these properties to accept decimal numbers.

This is the calculation I came up with before testing this (and the game crashing, crash log below)

amplifier | cumulative_modifier
-- | --
0.25 | 1.25

effect | amplifier | extra health | [formula](https://github.com/WesCook/Nutrition/blob/9e3e743a9a1b295ba9270aa56dea5bdfdaccbdc1/src/main/java/ca/wescook/nutrition/potions/PotionToughness.java#L15-L17)
-- | -- | -- | --
Toughness I | 0.25 | 5.00 | (0.25+1)*4.0
Toughness II | 1.50 | 10.00 | (1.50+1)*4.0
Toughness III | 2.75 | 15.00 | (2.75+1)*4.0
Toughness IV | 4.00 | 20.00 | (4.00+1)*4.0
Toughness V | 5.25 | 25.00 | (5.25+1)*4.0

(In this case, the 5th level of Toughness will **_not_** be used)

**Crash log:** https://pastebin.com/NAEcYiEV

Thank you in advance :+1:

**Comment by WesCook** [comment]
Hey sharkykh,

Thanks for the great report/question.

Effects can't received decimal values as a limitation of the game.  For instance if you entered "0.5 strength", the game wouldn't know how to interpret that.

However if you're looking to be more granular with the addition of hearts, I did add a custom effect specifically for that called `Nourished`.  Each level will add one half-heart, so you have more control over your health.

https://github.com/WesCook/Nutrition/wiki/New-Potion-Effects

Swapping out `toughness` for `nourished` and increasing the amplifier should offer what you're after.

Do note the default "Toughness" effect also mildly boosts armor toughness and attack speed, but it's much less significant than the heart increase.

Does that solve the problem for you?  Thanks.

**Comment by sharkykh** [comment]
> Thanks for the great report/question.

Thank you for responding!

_Full Disclosure:_ I don't have a dev environment for testing, nor do I code in Java / for MC.
I watch [Darkosto's Twitch stream](https://www.twitch.tv/Darkosto), he's developing a modpack with this mod in it - and the issue described above is one from his stream, which I wanted to tackle :)

> Effects can't receive decimal values as a limitation of the game. For instance if you entered "0.5 strength", the game wouldn't know how to interpret that.

I see. That's fair.
> However if you're looking to be more granular with the addition of hearts, I did add a custom effect specifically for that called `Nourished`. Each level will add one half-heart, so you have more control over your health.
> Swapping out `toughness` for `nourished` and increasing the amplifier should offer what you're after.

After opening this issue I took a look in the wiki, and I saw the `Nourished` effect,
although I believe you are incorrect - 
Each level of that effect will add 2 half-hearts, or 1 full heart, as can be seen in here:
https://github.com/WesCook/Nutrition/blob/9e3e743a9a1b295ba9270aa56dea5bdfdaccbdc1/src/main/java/ca/wescook/nutrition/potions/PotionNourished.java#L15-L17

(Unless I'm misreading something, which is totally possible!)

That being said, my issue still stands, because I still require decimal (point) numbers:

amplifier | cumulative_modifier
-- | --
0 | 1

effect | amplifier | extra health | formula
-- | -- | -- | --
Nourished I | 0 | 2.00 | (0+1)*2.0
Nourished II | 1 | 4.00 | (1+1)*2.0
Nourished III | 2 | 6.00 | (2+1)*2.0
Nourished IV | 3 | 8.00 | (3+1)*2.0
Nourished V | 4 | 10.00 | (4+1)*2.0

Again, the point is to have 4 levels of the effect, one for each nutrient, so Nourished V won't be used - making level 4 the highest with **10** full (20 half) extra hearts.

> Do note the default "Toughness" effect also mildly boosts armor toughness and attack speed, but it's much less significant than the heart increase.

I did notice (in the code) that `Toughness` adds other boosts as well, which, unfortunately (please correct  me if I'm wrong), can't be added separately in case I use `Nourished` for the health boost?

Let's say for the sake of this conversation that Darkosto still wanted to have the armor and attack speed boosts. That would require **another, different** potion effect, correct?

I was trying to find to have this option without considering changing the way you setup your custom potions (i.e. change it so it only gives 1 half heart per level - that would look weird for the player, I think)

**Comment by WesCook** [comment]
Oh, you're completely right.  I must have decided one heart was the smallest logical amount, but I see your argument for half-hearts.

If I were to make that change (and put out a warning as this unfortunately affects existing users), you would then be able to set the `cumulative_modifier` to 5 and it should work nicely with four nutrition groups.

Effect | Amplifier | Hearts
-- | -- | --
Nourished I | 5 | 2.5
Nourished II | 10 | 5.0
Nourished III | 15 | 7.5
Nourished IV | 20 | 10.0

Does that make sense?  If that's an agreeable solution, I can implement that change shortly.

Decimal numbers still won't be possible due to the risk of passing non-integers to the game.  That would be problematic.

>Let's say for the sake of this conversation that Darkosto still wanted to have the armor and attack speed boosts. That would require another, different potion effect, correct?

That's correct.

**Comment by sharkykh** [comment]
Definitely makes sense!
That sounds good to me.

Thanks!

**Comment by WesCook** [comment]
I've just released [v3.0.0](https://github.com/WesCook/Nutrition/releases/tag/v3.0.0) to add this feature (breaking change so a major version bump).  Hopefully this solves the problem for you and @Darkosto.

Let me know how it goes.  And thanks for the heads up that it's being included in a new pack.
