### ISSUE TITLE
[SUGGESTION] Config option to regenerate effects and nutrients

### ISSUE THREAD

**Issue by Sunconure11** [WesCook/Nutrition#58]
When updating, one has to remove their old configs. Would it be possible to add config options to regenerate effects and nutrients, that then switches itself off after regeneration? These configs should be separate, so one can regenerate nutrients without regenerating effects, for instance.

**Comment by WesCook** [comment]
Could you make an argument for why changing the config is easier than deleting the relevant folder?

Not opposed, just not sure it's any easier for end users.

**Comment by Sunconure11** [comment]
Wait, is it already intended to regenerate? Because I cleared old nutrients and it did not regenerate. Although I did not delete the folder, only it's contents.

**Comment by WesCook** [comment]
Right, it checks if the /nutrients and /effects folders exist.  If not, it'll recreate them from default configs (per the installed jar file).  You shouldn't ever need to nuke the main config file.

https://github.com/WesCook/Nutrition/blob/1.12/src/main/java/ca/wescook/nutrition/utility/Config.java#L114-L119

The readme might not be very clear about that.  I'd rather update that than change existing functionality.

**Comment by Sunconure11** [comment]
I see then.

**Comment by WesCook** [comment]
I've updated the readme (https://github.com/WesCook/Nutrition/commit/0508bcd6568865199888be919fcc16ec3d16e11b) to hopefully clarify this.  I'll close this issue if that's satisfactory.
