### ISSUE TITLE
[1.12.2 Nutrition v3.0.0] Hearts don't go away after dropping below Nourished threshhold

### ISSUE THREAD

**Issue by VallenFrostweaver** [WesCook/Nutrition#63]
In testing this, I can get the Nourished effect and gain hearts as you normally would. If I go below the nourished threshold (i.e. I die a few times) the hearts are still there (instead of gone) albeit they are empty and not able to regen. If I re-log, the hearts are gone as they should be. It seems to be a residual graphical error.

On a second note of similar stance, if I have a nourished effect going and drink a bucket of milk, the effects and additional hearts disappear for a few seconds then reappear (I was poisoned and drank milk to remove it and all effects were removed for a few seconds).

**Comment by WesCook** [comment]
Thanks for the report.  I was aware of the milk issue, but wasn't able to find a way to mark potions as "milk immune" at the time.  I'll need to look into if that's possible now, or if I can reapply potion effects at the time of drinking so it's seamless.

As for the other issue, that sounds more serious.  I don't recall seeing that in my testing but I'll see if I can reproduce + find a solution for it.

Thanks for the helpful report.

**Comment by Sunconure11** [comment]
I think The Vegan Option found a way to deal with that in regards to Thaumcraft's effects.

**Comment by WesCook** [comment]
I've been able to fix the milk issue by reapplying the effects when milk is consumed.  I've included this fix, as well as some food changes in the [v3.1.0 release](https://github.com/WesCook/Nutrition/releases/tag/v3.1.0).

As for the ghost heart issue, I spent a long time trying to track this down today.  As far as I can tell, this is actually a Forge bug.  It also occurs with `minecraft:health_boost`, so not just Nutrition-added health gain.

To test this yourself, you can compare vanilla 1.12 with the latest Forge release.  In chat type `/effect @p minecraft:health_boost`.  It will grant two hearts for 30 seconds.  Then type `/kill`.  If using a Forge client the two ghost hearts will remain until you relog.

I'm going to create a bug report on the Forge tracker and let the pros deal with it.  I'll also mark this issue as closed for now unless I've missed anything.

Thanks again for the reports.

**Comment by WesCook** [comment]
The first issue has now been fixed in Forge thanks to @williewillus.  The fix is available in Forge v14.23.2.2653.

https://github.com/MinecraftForge/MinecraftForge/issues/4824
