### ISSUE TITLE
[Suggestion] New effect to enable and disable natural health regeneration depending on nutrition level.

### ISSUE THREAD

**Issue by laserlemons** [WesCook/Nutrition#67]
It'd be cool if natural health regeneration true/false was a nutrition effect option.

**Comment by WesCook** [comment]
That does sound like a fun idea for modpacks.  Unfortunately however this idea is outside the scope of the mod, so it's not something I'd like to add.

Nutrition does work with potion effects from other mods however (and is designed for this), so a custom mod that adds the requested potion effect would be the way to go.  You might try asking some of the modders that focus on adding new potions like [Extra Alchemy](https://minecraft.curseforge.com/projects/extra-alchemy) if they'd be interested, or consider implementing it yourself.

Thanks for the suggestion, and I'm sorry if this is a disappointing answer.

**Comment by laserlemons** [comment]
Not disappointing at all! I didn't consider another mod adding that effect, I might even give it a go myself.
