### ISSUE TITLE
Tomatoes are not Vegetables!

### ISSUE THREAD

**Issue by JakeOTwitch** [WesCook/Nutrition#68]
Using Pam's HarvestCraft with the Nutrition mod labels Tomato as a vegetable but they are a fruit. I know this is nit picky but still...

**Comment by WesCook** [comment]
In terms of nutritional and culinary definitions, a tomato is closer to a vegetable than a fruit.  I'm less concerned with botanical definitions considering the theme of the mod.

For what it's worth, the [supreme court agrees](http://caselaw.findlaw.com/us-supreme-court/149/304.html).
