### ISSUE TITLE
Add support for Bird's Foods

### ISSUE THREAD

**Issue by Miaourt** [WesCook/Nutrition#69]
Hello, thanks for this great mods !

I'm trying to grasp a way to get items ID, but if someone is able do to it before me I would be really thankful :3 !
https://minecraft.curseforge.com/projects/birds-foods

**Comment by WesCook** [comment]
Hi @Technowix,

This mod looks like it would be a good addition.  There are a lot of food types, so if I were to add them myself it probably wouldn't be for a little while.

If you'd like to take a crack at it though, the best way would be to go into the Nutrition configs and enable this setting: `B:LogMissingNutrients=true`

Then check the log (either via console window or log file output).  It should display a list of all foods without nutrients that have been registered to the game.

You can submit a list either via pull request, or if it's easier for you then create a list of foods and their nutrients separately and I can merge it in manually.

One last thing.  You can check item IDs by pressing F3+H whilst in-game.  This will turn on advanced item tooltips which includes item IDs.

Thanks!

**Comment by Miaourt** [comment]
I will try to do it this week !

**Comment by WesCook** [comment]
Hey @Technowix,

I'm going to go ahead and close this issue for now.  If you make some progress on adding these items yourself, feel free to reply here and I'll get it, or submit it as a new Pull Request and I'll merge them in.

Cheers.

**Comment by Miaourt** [comment]
Sorry, got hyped but in front of the huge amount of work I dropped the idea ;u;'

**Comment by xAlicatt** [comment]
Where are the mod support jsons located in the file structure? I'm trying to see how complicated it would be to add Bird's Foods myself. I'm too tired to look at it right now, but I will see about getting you IDs sometime tomorrow so the mod support can be added.

**Comment by WesCook** [comment]
https://github.com/WesCook/Nutrition/tree/1.12/src/main/resources/assets/nutrition/configs/nutrients
