### ISSUE TITLE
Command Block Integration

### ISSUE THREAD

**Issue by shade28** [WesCook/Nutrition#70]
Currently there are two commands:

/nutrition get <nutrient> 
/nutrition set <nutrient> <value> 

These work great for testing, but will not work in command blocks or function files.
To make it work we need to add in a target, an add, and a subtract feature.

for example: 

/nutrition set <target> <value>
/nutrition add <target> <value>
/nutrition remove <target> <value>

This would allow for adventure packs that wish to be more flexible with the nutrition bars. Having a way to write the value of a nutrient to a scoreboard would be nice but is not 100% necessary. 
An example of that would be:

/scoreboard objectives add Protein nutrient.nutrition:protein

The <target> selector should work just as any vanilla target selector (name, @p, @a, @s)
The <value> would be a floating point number since nutrition seams to use a float for that.

**Comment by WesCook** [comment]
I've released the chat features (not scoreboard) into release v3.2.0 today.  Could you give it a try and let me know how it works for you?  Would appreciate the extra testing.

The new command format is: `/nutrition <player> <get/set/add/subtract/reset> <nutrient> <value>`

https://github.com/WesCook/Nutrition/releases/tag/v3.2.0

Thanks!

**Comment by shade28** [comment]
awesome. I was holding off on implementing digestion until you released it.
this is great.
