### ISSUE TITLE
Conquest Reforged compatibility

### ISSUE THREAD

**Issue by Irwe** [WesCook/Nutrition#73]
Conquest reforged mod is coming out for 1.12 very soon and will have a playable survival mode. 
Would be cool if the new food introduced in conquest reforged mod would be compatable with the nutrition mod. 

https://minecraft.curseforge.com/projects/conquest-reforged

https://twitter.com/ConReforged/status/988438761854808064

**Comment by WesCook** [comment]
Hi @Irwe,

This is a huge mod.  I haven't checked specifically but I'd guess they add a *lot* of food.  I'm really busy at the moment to take on new requests - especially for a big project like this - but I'd merge in any PR that attempted to add full support.  I'm sorry I don't have the time to do it myself.

Thanks for the suggestion though, and I'll keep an eye out if anyone is interested in taking this one on.
