### ISSUE TITLE
Foods that have a damage value don't keep attribute

### ISSUE THREAD

**Issue by Broam** [WesCook/Nutrition#76]
Example: Millenaire's Masa.

https://www.millenaire.org/wiki/Mayan:Masa

Tag it as grain and it looks to have grain 3% - but only the first bite. The food provides multiple meals by taking item damage. (The wiki says it has 1 use; but the 1.12 RC for Millenaire has it provide about 6 uses.)

It does not appear to provide the benefit on subsequent bites (it's not just a display bug).

**Comment by WesCook** [comment]
Nutrition treats item damage (metadata) as completely different foods, as many mods share IDs for different foods.  Could you try adding multiple entries for the food to see if that works?  eg.

```
mayan:masa:0
mayan:masa:1
mayan:masa:2
```

Thanks!

**Comment by WesCook** [comment]
I'm going to close this issue due to inactivity.

**Comment by Broam** [comment]
This works, thank you. Will work on getting you apull request for Millenaire shortly.
