### ISSUE TITLE
Zoo & Wild Animals Rebuilt is not supported

### ISSUE THREAD

**Issue by vrork** [WesCook/Nutrition#81]
The foods from this mod arent supported (they dont have any nutritional vallue)

**Comment by WesCook** [comment]
I've just tested the mod and it seems to be working fine.  It's likely you're using outdated configs with a newer version of the mod.  You'll need to delete the `/config/nutrition/nutrients` folder and let it regenerate.  The mod doesn't do this on its own to avoid overwriting people's customizations.
