### ISSUE TITLE
Latest Harvestcraft lacking nutrition values

### ISSUE THREAD

**Issue by Akitori** [WesCook/Nutrition#82]
Hiya, the newest foods by pam (as follows) are lacking nutrition values, even with a reloaded nutrition file.

Kale, Bacon Pancakes, Black Paella, Blazing Soup, Brioche Bun, Chicken Paella, Epic BLT, Escargot, Glistening Salad, Gourmet Beef Burger, Gourmet Beef Patty, Gourmet Mutton Burger, Gourmet Mutton Patty, Gourmet Pork Burger, Gourmet Pork Patty, Gourmet Venison Burger, Gourmet Venison Patty, Groiled Cheese Sandwich, Guiso, Jellied Eel, Kale Chips, Kohl und Pinkel, Meatloaf sandwich, Miner's Stew, Mob Soup, Netherstar on Toast, Pad Thai, Paradise Burger, Peanut Butter and Banana Sandwich, Peanut Butter Cup, Pinkel, Pitepalt, Sauerbraten, Slime Pie, Strawberry Rhubarb Pie, Tiropita, Rose Petal Tea

yeah...

**Comment by WesCook** [comment]
Gotchya.  I'll update those shortly.  Pam is a monster at adding new foods.

**Comment by WesCook** [comment]
I've released a new version which includes the latest Harvestcraft support.

https://github.com/WesCook/Nutrition/releases/tag/v3.4.0
