### ISSUE TITLE
Possible issue involving curse

### ISSUE THREAD

**Issue by Sunconure11** [WesCook/Nutrition#83]
While I'm aware your mod is approved for curse usage, I'm noticing something odd as of late.

I've been trying to push an update to my modpack, and it keeps getting rejected since it has your mod in it.
![curse rejection](https://user-images.githubusercontent.com/5614902/40384444-9034c6a6-5dd1-11e8-8702-6d324ac80b33.png)

**Comment by WesCook** [comment]
I think you'll have to contact Curse for this one.  The mod is on their [approved list](https://docs.google.com/spreadsheets/d/1lEwbJpwRVoZb8kr0OT-Wo4Yc7jAGWMGOFtfL0miCFmc/edit#gid=2137482024) as you say, but they must have some internal heuristic that is failing.  I don't know how their check works, but I doubt I've made any change that would interfere with it.

In the mean time, will an older version of the mod still work for you?

I'll leave this issue open for now in case others have this problem and come looking for a solution.  But it's something that Curse will need to correct on their end.

**Comment by WesCook** [comment]
@Sunconure11, has there been any change on this issue from Curse's end yet?

**Comment by Sunconure11** [comment]
Yes, the issue was resolved
