### ISSUE TITLE
Possible additional mod interactions.

### ISSUE THREAD

**Issue by LastXsile** [WesCook/Nutrition#86]
Currently playing the ATM3 pack and I've noticed things like the verdant heart charm from thaumcraft that sustains you with food doesn't have any way to give it nutrition far as I am aware. Also the fruit of grisaia from botania also doesn't give any nutrition. Both of these items take alot of work to obtain and are useless with nutrition on so any way to make them have nutrition values? If not could a way be implemented without a large amount of work on your part?

**Comment by Akitori** [comment]
I would argue that the fruit is more magical in nature, and not exactly nutritious.

**Comment by LastXsile** [comment]
I am not saying it should give all nutrition but some, it still is a fruit. Giving some small amount of fruit nutrition would be nice. Like I said however it's not something I am pushing hard for but it could be nice if its possible for additional mod support. My point in the matter isn't if it should have nutrition or not in the first place but the ability for it to have some in a none standard way saturation is handled with certain mods. That way packs could add it to such items with some sort of configuration.

**Comment by Hazmatik** [comment]
Another mod interaction I would suggest that is a bit more logical is Blood Magic's Ritual of the Satiated Stomach as it actually consumes food items to fill the players hunger and saturation would be nice if the nutrition value of the food items it consumes applies to the player when it consumes them. Not sure how hard that would be to do from a coding stand point.

**Comment by WesCook** [comment]
Thanks for the suggestions.  Unfortunately I don't think support for these items would be possible.  At least not without hacks.

These mods work by filling up the player's hunger directly, so there is never an event that I can tap into to add nutrition.  It's something that would probably work if you took a hamfisted approach and just watched for all items all the time, but this isn't very performant, nor does it match Nutrition's theme.

So I'm afraid you'll need to actually eat your food to gain nutrients for now.
