### ISSUE TITLE
Toughness not Tough 5 when all stats maxed

### ISSUE THREAD

**Issue by KindarConrath** [WesCook/Nutrition#87]
As shown in the images, when 1 stat is above 90% I get "Toughness" at 4 stats "Toughness 4" but for some reason, when I max all 5, I get "Toughness" again.

![2018-06-08_15 00 15](https://user-images.githubusercontent.com/5119861/41176436-5bcfaf92-6b2e-11e8-9495-f55786394161.png)
![2018-06-08_15 03 43](https://user-images.githubusercontent.com/5119861/41176437-5be1c84e-6b2e-11e8-87fb-60d309321d48.png)
![2018-06-08_15 04 25](https://user-images.githubusercontent.com/5119861/41176439-5bf0fa26-6b2e-11e8-8601-22823977dc73.png)

**Comment by WesCook** [comment]
Thanks for the detailed bug report.  However, this is actually a vanilla bug (or design choice?), and not something specific to Nutrition.

Some other mods modify the English strings to have later numbers show up (eg. [VanillaTweaks](https://github.com/strikerrocker/VanillaTweaks/blob/e4656c4871bddf505eff87004d9419522ae0e49e/src/main/resources/assets/vt/lang/en_us.lang#L300)), but I've just let it inherit the default behavior.

**Comment by KindarConrath** [comment]
Just so I understand, it gives a stronger bonus but just says "Toughness"?

**Comment by WesCook** [comment]
Correct.  It's just how vanilla displays larger potion numbers.

**Comment by renadi** [comment]
Will vanilla fix "fix" this issue?

**Comment by WesCook** [comment]
I don't know if VanillaFix will, but [Vanilla Tweaks](https://strikerrocker.github.io/VanillaTweaks/) should.  Other mods also address this such as Astral Sorcery, so it may not be needed in your modpack.
