### ISSUE TITLE
Accidentally opening GUI

### ISSUE THREAD

**Issue by Snownee** [WesCook/Nutrition#90]
https://github.com/WesCook/Nutrition/blob/8ff4fb79366b8152c3fb3ee203931c6c2e68a7d9/src/main/java/ca/wescook/nutrition/events/EventNutritionKey.java#L25
In this line, should use `ClientProxy.keyNutritionGui.isKeyDown()` instead. Because if the keybind is set to `NONE`, it may be equal in some special case (for example, the input method).

**Comment by WesCook** [comment]
Thank you very much for pointing that out.  Great report!
