### ISSUE TITLE
Millenaire: 0% foods

### ISSUE THREAD

**Issue by Broam** [WesCook/Nutrition#91]
Certain foods in Millenaire (Feta and Rasgulla are two that come to mind) seem to be treated as food, but restore 0% hunger and can be eaten anytime. When you assign a nutrient to this, it shows up as 0%.

Are there any plans to implement a "minimum nutrition"?

**Comment by WesCook** [comment]
No plans for "minimum nutrition", as this would create balance problems.  I am considering allowing an override for nutritional values, though.

Some examples of how that might look can be found in [this thread](https://github.com/WesCook/Nutrition/issues/54#issuecomment-381287924).

**Comment by WesCook** [comment]
Will mark as closed as minimum nutrition isn't a feature I'm interested in adding.  Thanks for the suggestion however.

I'm still pondering if I want to add food value overrides, but will address that elsewhere.
