### ISSUE TITLE
crash 

### ISSUE THREAD

**Issue by CharCharthemonkey** [WesCook/Nutrition#92]
[crash-2018-07-04_20.00.39-server.txt](https://github.com/WesCook/Nutrition/files/2164589/crash-2018-07-04_20.00.39-server.txt)
please fix and appearently its supposed to be player only from wat @raycoms and @wissi told me

**Comment by CharCharthemonkey** [comment]
https://github.com/ldtteam/minecolonies  is the minecolonies dev team github (the ones who said to message this on ure side

**Comment by WesCook** [comment]
Hi,

Can you try this using the latest version of Nutrition?  I'm not seeing any crashes when running the newest version of the mods together.

Thanks.

**Comment by CharCharthemonkey** [comment]
will try tho so far since 1st using both mods this only happened once but will keep an eye on it

**Comment by WesCook** [comment]
I'm pretty sure this issue was fixed in v2.8.0.  You were running v2.7.0 according to the crashlog.  If it occurs again in the latest version, please feel free to update this issue.
