### ISSUE TITLE
Custom nutrients bar name not showing properly

### ISSUE THREAD

**Issue by Pkyd** [WesCook/Nutrition#94]
![2018-07-11_02 35 42](https://user-images.githubusercontent.com/41084706/42533214-6e49dc12-84b3-11e8-849b-ee1b0fc6549f.png)
Tried to add a new custom nutrients bar, but instead showing only the name of the bar it happened like this
Later i tried changing the dairy bar name to milk and it also have the same issue

**Comment by WesCook** [comment]
Hi!

The name is actually a localized string so it can be translated into multiple languages.  As such a localization file needs to be loaded as well.  In singleplayer this can be done with a resource pack, but in multiplayer I suggest using a mod like [Resource Loader](https://minecraft.curseforge.com/projects/resource-loader).

Please see this section in the wiki for more.

https://github.com/WesCook/Nutrition/wiki/Nutrients#localizations
