### ISSUE TITLE
Nutrition for Altered Hunger Values

### ISSUE THREAD

**Issue by Zeklo** [WesCook/Nutrition#98]
I haven't been able to test it fully, since I don't have a complete grasp on how things are calculated, but it appears this mod doesn't adapt to mods altering the hunger value of items. So they keep their original nutritional values instead up adjusting up or down to compensate. 

Consider this a report if true, or a question otherwise.

**Comment by WesCook** [comment]
Nutritional value is based on restored hunger drumsticks.  So it should update dynamically to adjusted hunger values (eg. from HarvestCraft or HungerOverhaul).

https://github.com/WesCook/Nutrition/wiki/Frequently-Asked-Questions#how-is-nutrition-calculated

**Comment by WesCook** [comment]
Note if you test this and find that nutritional values are not correct, please update this report and I'll investigate.

**Comment by Zeklo** [comment]
I mention it because some values seem off. For example, prime beef from Animania is automatically changed by Hunger Overhaul and the nutrition value seems stagnant remaining at 10% despite the change.
![2018-08-05_10 18 16](https://user-images.githubusercontent.com/6024737/43688213-aa9c3576-9899-11e8-8265-d9c775eae43b.png)
I also went ahead and set a food's hunger value to 0, manually and the nutrition remains.
![2018-08-05_10 18 20](https://user-images.githubusercontent.com/6024737/43688215-ae752284-9899-11e8-88fa-a9fea04917d7.png)

**Comment by WesCook** [comment]
Okay, I will investigate.  Thank you.

**Comment by WesCook** [comment]
Apologies for the delay in looking into this.  I've now had a chance to do some testing.

I tried this with Harvestcraft and found that nutrition did update correctly.  Steak was 4.0 Protein in Vanilla, and 1.0 with Harvestcraft.

I then tested with Hunger Overhaul.  It seems that adjusted hunger values are indeed not being accurately reflected.

So Hunger Overhaul intercepts the food value upon eating, whereas Harvestcraft overwrites it completely.

Upon reflection, I think I'm currently following the best convention.  I am trusting the `getHealAmount` value from the `ItemFood`, as Minecraft provides it.  I'm sure it would be possible to tap into AppleCore and see what the new calculated food value is, but instead I'm going to suggest the users just adjust the `NutritionMultiplier` from my mod to match.  This seems a little bit cleaner and offers more control to the end-user.

If using a divider of four in HungerOverhaul (`S:foodHungerDivider=4.0`), then setting a nutrition multiplier of 0.25 will match the same values (S:NutritionMultiplier=0.25).

Thanks for the report!

**Comment by Controverso** [comment]
@WesCook Sorry for bothering after so long a time but the `S:foodHungerDivider=4.0` only applies to foods from other mods, and as for vanilla foods it has a preset hunger value. I can modify foods from mods manually by the configs of HungerOverhaul and the nutritions updates perfectly fine, but it doesn't work on the vanilla foods, or not for me at least.
For example, ![1](https://user-images.githubusercontent.com/86462524/124726056-033a8580-df40-11eb-8e66-f62afb329e86.png)

**Comment by Controverso** [comment]
@WesCook Sorry for bothering after so long a time but the S:foodHungerDivider=4.0 only applies to foods from other mods, and as for vanilla foods it has a preset hunger value. I can modify foods from mods manually by the configs of HungerOverhaul and the nutritions updates perfectly fine, but it doesn't work on the vanilla foods, or not for me at least.
For example, 
![image](https://user-images.githubusercontent.com/86462524/124727383-3df0ed80-df41-11eb-92e3-fd39cf0fc9eb.png)
the nutrition value for vanilla foods just won't update like foods from mods.

**Comment by WesCook** [comment]
I'm not sure why that might be, but there isn't anything in Nutrition that has special casing for vanilla foods.  It will calculate the nutrition amount on-the-fly by looking at the hunger value (ie. how many honches it fills).  If another mod is modifying those values, it should be reflected correctly by Nutrition.

It sounds like it might be a Hunger Overhaul bug, but I don't know enough about the mod to say for sure.  It could be by design, or a conflict with some other mod that's installed.
