### ISSUE TITLE
[Thought] Negative food category

### ISSUE THREAD

**Issue by Kremnari** [WesCook/Nutrition#99]
Have you given any thoughts to negative food categories?  Some examples: sweets, fat, poison (monster parts).  In the [nutrient].json you could add an inverted property which causes effects to be applied in the opposite manner (perhaps just evaluated as 100 - value behind the scenes).

Perhaps even combining this with a scaling property so foods won't add a lot of a given nutrient, but it takes slower to burn (gain_scale and burn_scale).

This could also open up some interesting stat effects if the modder adds a "magical" and "taint" category.

Loving the mod, thank you!

**Comment by WesCook** [comment]
Hey Kremnari,

Thanks for your suggestion.

Unless I'm misunderstanding you though, negative nutrients are most definitely possible in the current system.  Let's take your poison example.

	{
		"name": "poisonous",
		"icon": "minecraft:spider_eye",
		"color": "003300",
		"food": {
			"items": [
				"minecraft:spider_eye",
				"minecraft:zombie_flesh",
				"thaumcraft:zombie_brain"
			]
		}
	}

This will increment as the player eats poisonous foods.  Then we apply the `minecraft:poison` effect when it's within a certain threshold:

	{
		"name": "poison",
		"potion": "minecraft:poison",
		"minimum": 60,
		"maximum": 100,
		"detect": "all",
		"nutrients": ["poisonous"]
	}

And now when the player eats enough poisonous foods, they'll eventually get the poison potion effect applied.

Does that cover your request, or is there more to it?

>Perhaps even combining this with a scaling property so foods won't add a lot of a given nutrient, but it takes slower to burn (gain_scale and burn_scale).

Currently you can set the decay rate of specific nutrients, but not a multiplier when eating a food.  That's a good idea though!

**Comment by Kremnari** [comment]
Actually, that does cover it.  I must've missed the "nutrient" property for effects.

To clarify, the multiplier for eating food would be to fine tune a nutrient vs it's hunger value.  ( I read that it was an automatic calculation)

**Comment by XvBUSHvX** [comment]
Not to butt in to another conversation, but this topic is actually relevant, albeit indirectly, to something I was curious about.

I recently came across another mod named ["Food Funk"](https://github.com/Stormwind99/FoodFunk) that immediately made me think about how I could use their mechanic with this mod.

It provides decay on food. If it were possible to add a category as referenced in your post above that would calculate based off of something like the saturation/%decay and applies saturation-saturation/%decay to the foods original nutritional groups. That would be an interesting element of immersion.

**Comment by WesCook** [comment]
That might be possible with an API I'm in the planning stages of right now.  I'll keep the mod in mind, but can't promise support going forward.

**Comment by XvBUSHvX** [comment]
No worries, every bit is appreciated. The dev commented on their project page they are open to colabs. I'm willing to make an issue with them linking to this if you're interested.

**Comment by WesCook** [comment]
Sure thing.  You'd probably be better off pointing them to #74 as that's where planning for the API is.  I wouldn't expect any compat in the near-future, but it would make sense to scope things out so compat will be possible later.

I'm going to close this issue for now as I think the request has been addressed.  Though @Kremnari if you'd like to open a separate request for a nutrition modifier on eating food, that'd be just fine.  I'm surprised that request hasn't come up before.
